import test from 'node:test';
import assert from 'node:assert/strict';
import {createAuthService,authErrorKey} from '../src/browser/auth-service.mjs';
function harness(){const calls=[];let next={data:{user:{id:'test-only',email:'test@example.invalid'}},error:null};const auth=new Proxy({},{get:(_,method)=>async (...args)=>{calls.push({method,arg:args[0],options:args[1]});return next;}});return {calls,set:r=>{next=r;},service:createAuthService({auth},'https://moosetvs.com')};}
test('signup delegates password handling and localized confirmation to Supabase',async()=>{const h=harness();h.set({data:{session:null},error:null});await h.service.signUp('test@example.invalid','example-test-password',' Test ','/he/account/');assert.equal(h.calls[0].method,'signUp');assert.equal(h.calls[0].arg.options.emailRedirectTo,'https://moosetvs.com/he/account/');assert.equal(h.calls[0].arg.options.data.display_name,'Test');});
test('login and protected account verification use the provider, not a local auth flag',async()=>{const h=harness();await h.service.signIn('test@example.invalid','example-test-password');await h.service.user();assert.deepEqual(h.calls.map(x=>x.method),['signInWithPassword','getUser']);h.set({data:{user:null},error:{code:'session_not_found'}});await assert.rejects(h.service.user());});
test('forgot password uses the localized secure callback and propagates mail failures',async()=>{const h=harness();await h.service.reset('test@example.invalid','/ar/reset-password/');assert.equal(h.calls[0].method,'resetPasswordForEmail');assert.equal(h.calls[0].options.redirectTo,'https://moosetvs.com/ar/reset-password/');h.set({error:{code:'email_address_not_authorized'}});await assert.rejects(h.service.reset('test@example.invalid','/reset-password/'));});
test('password update, profile update and logout await provider success',async()=>{const h=harness();await assert.rejects(h.service.updatePassword('short'));assert.equal(h.calls.length,0);await h.service.updatePassword('long-test-password');await h.service.updateName('Updated');await h.service.signOut();assert.deepEqual(h.calls.map(x=>x.method),['updateUser','updateUser','signOut']);assert.deepEqual(h.calls[2].arg,{scope:'local'});h.set({error:{code:'invalid_credentials'}});await assert.rejects(h.service.signIn('test@example.invalid','wrong'));});
test('errors are clear and do not display provider details or secrets',()=>{assert.equal(authErrorKey({code:'invalid_credentials'}),'The email or password is incorrect.');assert.equal(authErrorKey({code:'otp_expired'}),'This link or session has expired. Request a new reset link.');assert.equal(authErrorKey({message:'private internal error'}),'We couldn’t complete that request. Please try again or contact us.');});
