import {icon,link,href,pageHero} from './layout.mjs';
import {field} from './forms.mjs';
export function accountPages(ctx){
 const t=ctx.t;
 const modes=[['sign-in','Sign In','Welcome back.','Sign in to your MooseTVs account.'],['sign-up','Sign Up','A good place to begin.','Create your account for what comes next.'],['forgot-password','Forgot Password','Let’s get you back in.','We’ll send you a link to reset your password.'],['reset-password','Reset Password','A fresh start.','Choose a new password for your account.']];
 const result=modes.map(([path,title,headline,description])=>({path,title:ctx.text(title),description:ctx.text(description),noindex:true,body:`<section class="auth-layout wrap"><div class="auth-story"><p class="eyebrow">MOOSETVS / ${t('Your workspace')}</p><h1>${t(headline)}</h1><p>${t(description)}</p><div class="auth-art" aria-hidden="true"><div></div><div></div><div></div><span>m.</span></div><p class="auth-footnote">${t('Thoughtful technology.')} ${t('Built for your next chapter.')}</p></div><div class="auth-panel"><span class="auth-icon">${icon(path.includes('password')?'lock':'user')}</span><h2>${t(title)}</h2><p id="auth-status" class="form-status" role="status" aria-live="polite">${t('Connecting securely…')}</p><noscript><p>${t('Enable JavaScript to use secure account features.')}</p></noscript><form data-auth-form="${path}" class="auth-form"><fieldset disabled>${path==='sign-up'?field(ctx,'Name','name','text',true,'name'):''}${path!=='reset-password'?field(ctx,'Email','email','email',true,'email'):''}${path!=='forgot-password'?`<label for="password">${t(path==='reset-password'?'New password':'Password')}<div class="password-field"><input id="password" name="password" type="password" aria-label="${t(path==='reset-password'?'New password':'Password')}" required minlength="${path==='sign-in'?1:12}" maxlength="128" autocomplete="${path==='sign-in'?'current-password':'new-password'}" aria-describedby="password-help"><button type="button" data-show-password aria-pressed="false">${t('Show')}</button></div></label><p class="form-note" id="password-help">${t(path==='sign-in'?'Use your account password.':'Use at least 12 characters.')}</p>`:''}${path==='reset-password'?`<label for="confirm-password">${t('Confirm password')}<input id="confirm-password" name="confirm_password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label>`:''}${path==='sign-up'?`<label class="checkbox"><input type="checkbox" name="terms" required><span>${t('I agree to the')} <a href="${href('terms',ctx.lang)}">${t('Terms')}</a> ${t('and')} <a href="${href('privacy',ctx.lang)}">${t('Privacy notice')}</a>.</span></label>`:''}<button type="submit" class="button">${t(path==='forgot-password'?'Send reset link':path==='reset-password'?'Update password':title)}${icon('arrow')}</button></fieldset></form><div class="auth-links">${path==='sign-in'?`${link('Forgot Password','forgot-password',ctx)}<p>${t('New to MooseTVs?')} ${link('Create an account','sign-up',ctx)}</p>`:`${link('Back to Sign In','sign-in',ctx)}`}</div></div></section>`}));
 result.push({path:'account',title:ctx.text('Your account'),description:ctx.text('Your MooseTVs account and future project workspace.'),noindex:true,body:`<section class="wrap account-page"><div class="account-heading"><div><p class="eyebrow">${t('Your workspace')}</p><h1>${t('Welcome back.')}</h1></div><button class="button secondary" data-signout hidden>${t('Sign Out')}</button></div><p id="auth-status" class="form-status" role="status" aria-live="polite">${t('Checking your session…')}</p><noscript><p>${t('Enable JavaScript to use secure account features.')}</p></noscript><div data-account-content hidden><div class="account-banner">${icon('user')}<div><h2 data-user-name></h2><p data-user-email dir="ltr"></p></div><span class="account-badge">${t('Your account')}</span></div><div class="account-grid">${[['grid','My Projects','Your future projects will have a home here.'],['chat','Requests / Quotes','A place for future project conversations.'],['box','Digital Products','Your future tools and downloads, together.']].map(([i,n,p])=>`<article class="account-card">${icon(i)}<span class="status-pill">${t('Coming soon')}</span><h2>${t(n)}</h2><p>${t(p)}</p></article>`).join('')}</div><section class="settings-panel"><div><p class="eyebrow">${t('Settings')}</p><h2>${t('Make yourself at home.')}</h2><p>${t('Update your name or send yourself a password reset link.')}</p></div><form data-profile-form><label for="display-name">${t('Name')}<input id="display-name" name="display_name" autocomplete="name" maxlength="80" required></label><button type="submit" class="button secondary">${t('Save changes')}</button><button type="button" class="text-link" data-reset-account>${t('Send password reset email')}</button><p class="form-status" role="status" aria-live="polite"></p></form></section></div></section>`});
 return result;
}
