// Add projects here. All portfolio views use this single collection.
// Screenshots must be local /images/... assets with descriptive alt text.
export const projects = [
  {title:'Spaces, before you visit',slug:'spatial-explorer',category:'Website',shortDescription:'Explore a property through a more useful digital experience.',fullDescription:'A property-exploration concept with a room-by-room plan and clear spatial details. An alternative to a static listing, designed to help visitors understand a space before arranging a visit. This is an interface concept, not an available property or a live tour.',technologies:['Interactive design','SVG','Responsive interfaces'],screenshots:[],status:'Concept project',demoUrl:null,githubUrl:null,featured:true,year:2026,visual:'spaces'},
  {title:'A voice, made useful',slug:'voice-concierge',category:'AI Automation',shortDescription:'A hands-free way to find answers and plan the next step.',fullDescription:'A voice-concierge interface concept for common questions and appointment discovery, with a clear handoff to a person. No microphone is activated and no audio is recorded; the waveform is an illustration of a possible experience.',technologies:['Voice interface design','Conversation design','Human handoff'],screenshots:[],status:'Concept project',demoUrl:null,githubUrl:null,featured:true,year:2026,visual:'voice'},
  {title:'From shelf to doorstep',slug:'order-journey',category:'Business System',shortDescription:'A thoughtful journey from stockroom to customer.',fullDescription:'An order-fulfilment concept that makes picking, packing and dispatch easy to follow. Designed for a small product business that needs a clearer connection between inventory and customer updates. All order information is fictional.',technologies:['Product design','Inventory workflows','Customer experience'],screenshots:[],status:'Concept project',demoUrl:null,githubUrl:null,featured:true,year:2026,visual:'fulfilment'},
  {title:'The connected workspace',slug:'connected-workspace',category:'Dashboard',shortDescription:'A clearer view of every lead, task and next step.',fullDescription:'A concept business dashboard that brings a sample pipeline into one focused workspace. Search and filter fictional leads in the interactive demo.',technologies:['JavaScript','HTML / CSS','Data visualization'],screenshots:[],status:'Concept project',demoUrl:'/demos/dashboard/',githubUrl:null,featured:false,year:2026,visual:'dashboard'},
  {title:'From enquiry to action',slug:'enquiry-automation',category:'AI Automation',shortDescription:'A thoughtful workflow for the moments after hello.',fullDescription:'A simulated workflow that turns an enquiry into an organized record and a draft follow-up. The demo makes each step visible; no external service is connected.',technologies:['Workflow design','JavaScript','API-ready'],screenshots:[],status:'Concept project',demoUrl:'/demos/automation/',githubUrl:null,featured:false,year:2026,visual:'automation'},
  {title:'Olive & Ember',slug:'olive-and-ember',category:'Website',shortDescription:'A welcoming digital home for a neighborhood restaurant.',fullDescription:'A fictional restaurant experience with a filterable menu and a sample reservation request. Designed to make discovering the menu and planning a visit feel effortless.',technologies:['Responsive design','HTML / CSS','JavaScript'],screenshots:[],status:'Concept project',demoUrl:'/demos/restaurant/',githubUrl:null,featured:false,year:2026,visual:'restaurant'},
  {title:'A little time for you',slug:'studio-booking',category:'Business System',shortDescription:'Simple scheduling, from first visit to the admin view.',fullDescription:'A booking concept for a fictional studio. Create a sample appointment, see it in the admin view and cancel it to free a slot. All sample data stays in this page.',technologies:['JavaScript','Accessible forms','Scheduling'],screenshots:[],status:'Concept project',demoUrl:'/demos/booking/',githubUrl:null,featured:false,year:2026,visual:'booking'},
  {title:'A helpful first conversation',slug:'support-assistant',category:'AI Automation',shortDescription:'Quick answers with a clear path to a real person.',fullDescription:'A scripted support concept with common questions and a sample human handoff. It demonstrates an interaction pattern, not a live AI service.',technologies:['Conversation design','JavaScript','Human handoff'],screenshots:[],status:'Concept project',demoUrl:'/demos/support/',githubUrl:null,featured:false,year:2026,visual:'automation'},
  {title:'Northline',slug:'northline',category:'Website',shortDescription:'A confident first impression for a local business.',fullDescription:'A fictional home-services website with a focused offer and a short enquiry flow. Demo enquiries are never sent to a real business.',technologies:['HTML / CSS','JavaScript','Responsive design'],screenshots:[],status:'Concept project',demoUrl:'/demos/business/',githubUrl:null,featured:false,year:2026,visual:'website'},
  {title:'The business starter',slug:'business-starter',category:'Digital Products',shortDescription:'A considered starting point for your next website.',fullDescription:'A downloadable, responsive HTML starter with an MIT license. Customize the name, content, colors and contact details before publishing.',technologies:['HTML / CSS','MIT license'],screenshots:[],status:'Free template',demoUrl:'/demos/template/',githubUrl:null,featured:false,year:2026,visual:'website'}
];
export const services = [
  {slug:'ai-automation',name:'AI Automation',icon:'spark',description:'Less repetitive work. More time for what matters.',headline:'Let the routine run itself.',intro:'Thoughtful automations that connect your tools and give your team time back.',benefits:['Less manual work','Faster responses','Human oversight'],builds:['Support assistants','Lead follow-ups','Connected workflows','Document processing'],example:'An enquiry arrives, the details are organized and your team receives a ready-to-review follow-up.',project:'enquiry-automation'},
  {slug:'web-development',name:'Web Development',icon:'globe',description:'Beautiful, fast websites that turn interest into action.',headline:'Your best first impression.',intro:'A clear, fast and memorable website, built around your business and your customers.',benefits:['Mobile-first design','Clear customer journeys','Search-ready foundations'],builds:['Business websites','Landing pages','Booking experiences','Multilingual websites'],example:'A customer discovers your services, finds what they need and sends an enquiry in minutes.',project:'olive-and-ember'},
  {slug:'custom-software',name:'Custom Software',icon:'code',description:'Tools shaped around the way your business works.',headline:'A better way to work.',intro:'Focused software that brings your people, processes and information together.',benefits:['One connected workspace','Built around your team','Room to grow'],builds:['Business dashboards','Customer portals','Internal tools','API integrations'],example:'Your team sees every enquiry and its next step in one shared, easy-to-use workspace.',project:'connected-workspace'},
  {slug:'digital-products',name:'Digital Products',icon:'box',description:'Practical templates and tools. A smarter starting point.',headline:'Start a step ahead.',intro:'Useful building blocks for your next idea, with future SaaS products shaped by real business needs.',benefits:['A faster start','Reusable foundations','Clear documentation'],builds:['Website templates','Automation starters','Reusable components','Future SaaS tools'],example:'Download a free website starter, make it yours and build from a solid foundation.',project:'business-starter'}
];
export const industries = [
  ['restaurants','Restaurants','Menus, reservations and a warmer welcome.','coffee'],
  ['gyms','Gyms','Membership enquiries and simpler scheduling.','activity'],
  ['salons','Salons','Bookings that fit the way you work.','spark'],
  ['clinics','Clinics','Clear information and easier appointment requests.','shield'],
  ['real-estate','Real Estate','Property showcases and organized enquiries.','home'],
  ['automotive','Automotive','From vehicle discovery to a service request.','car'],
  ['local-stores','Local Businesses','A stronger local presence, online.','shop'],
  ['professional-services','Professional Services','Better client journeys. Less routine admin.','briefcase']
];
export const plans = [
  {name:'Starter Website',price:269,description:'A focused home for your business.',features:['Single-page website','Mobile-ready design','Contact form']},
  {name:'Business Website',price:549,description:'A complete presence. Built to grow.',features:['Up to 5 core pages','Search-ready foundations','Enquiry forms'],featured:true},
  {name:'AI Automation',price:319,description:'One workflow. A better working day.',features:['One focused workflow','Tool integration','Testing & handover']}
];
export const steps = [['Discover','Understand your goals.'],['Plan','Agree on a clear scope.'],['Build','Bring the idea to life.'],['Test','Refine every detail.'],['Launch','Go live with confidence.']];
export const problems = [['clock','Too much manual work','Give routine tasks a better system.'],['chat','Slow customer responses','Make the first answer faster.'],['globe','Outdated website','Show the quality of your business.'],['flow','Lost leads','Give every enquiry a next step.'],['grid','Scattered business data','Bring the useful details together.'],['calendar','Repetitive admin','Make more room for your team.']];
