import {icon,link,pageHero,cta,href} from './layout.mjs';
import {projects} from './data.mjs';
export function demoPages(ctx){
 const t=ctx.t;
 const status='<p class="form-status" role="status" aria-live="polite"></p>';
 const field=(label,name,type='text')=>`<label>${t(label)}<input name="${name}" type="${type}" required maxlength="100"${type==='date'?' data-future-date':''}></label>`;
 const select=(label,name,options,attrs='')=>`<label>${t(label)}<select name="${name}" ${attrs}>${options.map(([v,l])=>`<option value="${v}">${t(l)}</option>`).join('')}</select></label>`;
 const demoButton=label=>`<button class="button" type="submit">${t(label)}</button>`;
 const panels={
 support:`<div class="demo-grid"><section class="demo-panel"><p class="eyebrow">${t('Scripted assistant')}</p><h2>Cedar Studio</h2><div id="chat-log" class="chat-log" role="log" aria-live="polite" aria-label="${t('Demo conversation')}"><div class="bubble">${t('Hello! Ask about hours, prices or a first visit.')}</div></div><div class="quick-questions">${['Opening hours','Class prices','First visit'].map(q=>`<button type="button" data-question="${q}">${t(q)}</button>`).join('')}</div><form id="chat-form" class="chat-form"><label class="sr-only" for="chat-input">${t('Your question')}</label><input id="chat-input" required maxlength="300" placeholder="${t('Your question')}">${demoButton('Send')}</form><button type="button" class="text-button" id="chat-reset">${t('Reset conversation')}</button></section><section class="demo-panel"><h2>${t('A person, when you need one.')}</h2><p class="panel-copy">${t('Try a sample handoff. Nothing is sent.')}</p><form id="handoff-form" class="demo-form">${field('Sample name','name')}${field('Sample email','email','email')}${select('Interested in','interest',[['First visit','First visit'],['Membership','Membership'],['Personal training','Personal training']])}${demoButton('Prepare sample handoff')}${status}</form></section></div>`,
 booking:`<div class="demo-grid"><section class="demo-panel"><h2>${t('Make time for yourself.')}</h2><form id="booking-form" class="demo-form">${select('Service','service',[['Intro consultation','Intro consultation'],['Personal training','Personal training'],['Studio tour','Studio tour']])}<div class="grid two">${field('Date','date','date')}${select('Time','time',['09:00','10:30','12:00','14:00','15:30'].map(x=>[x,x]))}</div>${field('Sample name','name')}${demoButton('Create demo booking')}${status}</form></section><section class="demo-panel"><p class="eyebrow">${t('Admin view')}</p><h2>${t('Appointments')}</h2><div id="bookings-list" aria-live="polite"><p class="empty-state">${t('No sample appointments yet.')}</p></div></section></div>`,
 restaurant:`<div class="restaurant-demo"><div class="restaurant-hero"><p>OLIVE & EMBER</p><h2>${t('Good food.')}<br>${t('Better company.')}</h2><p>${t('Seasonal. Simple. Beautiful.')}</p></div><section class="restaurant-section"><h2>${t('The menu')}</h2><div class="filter-buttons">${[['all','All'],['plates','Small plates'],['mains','Mains'],['sweet','Dessert']].map(([v,l],i)=>`<button data-menu-filter="${v}" aria-pressed="${i===0}">${t(l)}</button>`).join('')}</div><div class="grid two menu-dishes">${[['plates','Whipped hummus','$9'],['plates','Roasted vegetables','$12'],['mains','Charred cauliflower','$19'],['mains','Lemon chicken','$24'],['sweet','Orange cake','$8'],['sweet','Chocolate mousse','$9']].map(([cat,name,price])=>`<article data-menu-category="${cat}"><h3>${t(name)}</h3><strong dir="ltr">${price}</strong></article>`).join('')}</div><p class="form-note">${t('Fictional menu. Ingredients and allergens must be confirmed with a real restaurant.')}</p></section><section class="restaurant-section"><h2>${t('A seat at the table')}</h2><form id="reservation-form" class="demo-form"><div class="grid two">${field('Sample name','name')}${select('Party size','party',['2','3','4','5','6'].map(x=>[x,x]))}${field('Date','date','date')}${select('Time','time',['18:00','19:00','20:00'].map(x=>[x,x]))}</div>${demoButton('Try reservation request')}${status}</form></section></div>`,
 business:`<div class="business-demo"><div class="business-hero"><p class="eyebrow">NORTHLINE / ${t('Concept project')}</p><h2>${t('Thoughtful spaces.')}<br>${t('Beautifully made.')}</h2><p>${t('A confident first impression for a local business.')}</p></div><section class="business-section"><div class="grid three">${['Repairs','Painting','Home improvements'].map(x=>`<article><h3>${t(x)}</h3></article>`).join('')}</div><form id="business-form" class="demo-form"><h2>${t('Let’s talk.')}</h2>${field('Sample name','name')}${select('Service','service',['Repairs','Painting','Home improvements'].map(x=>[x,x]))}<label>${t('Project description')}<textarea name="details" rows="3" minlength="10" maxlength="1000" required></textarea></label>${demoButton('Try enquiry')}${status}</form></section></div>`,
 dashboard:`<section class="demo-panel dashboard-panel"><div class="panel-heading"><div><p class="eyebrow">${t('Sample data')}</p><h2>${t('Your business. Connected.')}</h2></div></div><div class="dashboard-filters"><label>${t('Search leads')}<input type="search" id="lead-search" placeholder="${t('Name, company or service')}"></label>${select('Status','status',[['all','All'],['New','New'],['In progress','In progress'],['Won','Won']],'id="lead-status"')}<button class="button secondary" id="reset-dashboard">${t('Reset filters')}</button></div><div id="dashboard-metrics" class="grid three dashboard-metrics" aria-live="polite"></div><div class="dashboard-chart"><h3>${t('Leads by stage')}</h3><div id="pipeline-chart"></div></div><div class="table-scroll"><table><caption class="sr-only">${t('Sample data')}</caption><thead><tr>${['Name','Company','Service','Status','Potential value'].map(x=>`<th scope="col">${t(x)}</th>`).join('')}</tr></thead><tbody id="lead-rows"></tbody></table></div><p class="form-note">${t('Values are fictional. Potential value is not revenue.')}</p></section>`,
 automation:`<div class="demo-grid"><section class="demo-panel"><p class="eyebrow">${t('Workflow concept')}</p><h2>${t('From enquiry to action')}</h2><p class="panel-copy">${t('Choose a sample enquiry. No external systems are connected.')}</p>${select('Sample enquiry','scenario',[['website','A restaurant needs a website'],['automation','A salon needs booking follow-ups'],['software','A studio needs a dashboard']],'id="workflow-scenario"')}<div class="button-row"><button class="button" id="run-workflow">${t('Run demo workflow')}</button><button class="button secondary" id="reset-workflow">${t('Reset')}</button></div><div id="workflow-result" class="result-box" role="status">${t('Ready when you are.')}</div></section><section class="demo-panel"><ol class="simulation-steps">${[['mail','Enquiry received'],['spark','Request organized'],['grid','Record prepared'],['mail','Follow-up drafted'],['check','Ready for review']].map(([i,n])=>`<li><span class="step-icon">${icon(i)}</span><h3>${t(n)}</h3><span class="simulation-status">${t('Waiting')}</span></li>`).join('')}</ol></section></div>`,
 template:`<div class="demo-grid"><section class="demo-panel"><p class="eyebrow">HTML / CSS</p><h2>${t('The business starter')}</h2><p class="panel-copy">${t('A downloadable, responsive HTML starter with an MIT license. Customize the name, content, colors and contact details before publishing.')}</p><a class="button" href="/downloads/moosetvs-business-starter.html" download>${t('Download free starter')}${icon('arrow')}</a><p class="form-note">${t('The downloadable template is in English and can be edited in any text editor.')}</p></section><section class="demo-panel"><h2>${t('Start a step ahead.')}</h2><ol class="template-steps">${['Download the HTML file.','Make the content and colors your own.','Review, test and publish.'].map(x=>`<li>${t(x)}</li>`).join('')}</ol><a class="text-link" href="/downloads/LICENSE.txt">${t('Read the MIT license')}</a><div class="button-row">${link('Request Quote','quote',ctx,'button secondary')}</div></section></div>`
 };
 return Object.entries(panels).map(([id,body])=>{const p=projects.find(p=>p.demoUrl===`/demos/${id}/`);return {path:`demos/${id}`,title:`${ctx.text(p.title)} — ${ctx.text('Demo')}`,description:ctx.text(p.fullDescription),legacyDemo:true,body:pageHero(ctx,'Interactive demo',p.title,p.shortDescription)+`<div class="wrap demo-notice">${icon('code')}<span>${t('Concept project. Fictional data. Demo actions stay in this page and do not contact anyone.')}</span></div><section class="section wrap demo-surface" data-demo="${id}">${body}</section>`+cta(ctx)};});
}
