import {icon,link,heading,cta} from './layout.mjs';
import {projects,problems} from './data.mjs';
import {serviceCards,visual,projectCards,industryCards,process,priceCards} from './sections.mjs';
import {validStage,priceJourney} from './valid.mjs';

export function homePage(ctx){
 const t=ctx.t;
 const headline=['Build smarter.','Automate more.','Grow faster.'];
 return `<section class="hero" data-moose-mood="curious"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span>${t('Thoughtful technology. Real possibility.')}</p><h1 data-type-heading aria-label="${headline.map(t).join(' ')}">${headline.map((text,i)=>`<span class="hero-type-line${i===2?' hero-type-em':''}" aria-hidden="true"><span class="type-layout">${t(text)}</span><span class="type-ink">${t(text)}</span></span>`).join('')}</h1><p class="hero-description">${t('We build AI automations, websites and custom software for modern businesses.')}</p><div class="button-row">${link('Get a Quote','quote',ctx,'button')}${link('View Our Work','work',ctx,'button outline-light')}</div><p class="hero-footnote"><span></span>${t('Built around your business. Designed for what’s next.')}</p>${validStage(ctx,'hello')}</div><div class="hero-visual" data-hero-dashboard>${visual('dashboard',ctx,true)}<div class="visual-caption"><span>01 — ${t('THE CONNECTED BUSINESS')}</span><span>${t('Interface concept')}</span></div></div></div><div class="wrap hero-bottom"><span>${t('From the first idea to the everyday details.')}</span><span>${t('AI. Websites. Software. Possibility.')}</span></div></section>
 <section class="section wrap" data-moose-mood="happy" id="expertise">${heading(ctx,'Our expertise','Better tools. Bigger possibilities.','Four ways to move your business forward.',link('Explore services','services',ctx))}${validStage(ctx,'expertise')}${serviceCards(ctx)}</section>
 <section class="section section-tint" data-moose-mood="amazed" id="possibilities"><div class="wrap">${heading(ctx,'Selected concepts','A glimpse of what’s possible.','Ideas made tangible. Explore the experiences we can build.',link('View all work','work',ctx))}${validStage(ctx,'strong')}${projectCards(ctx,projects.filter(p=>p.featured))}<p class="section-note">${t('Concept projects with sample data. Real client work will be added here.')}</p></div></section>
 <section class="section wrap">${heading(ctx,'Less friction. More focus.','Make room for the work that matters.')}<div class="problems-grid">${problems.map(([i,h,p])=>`<article>${icon(i)}<h3>${t(h)}</h3><p>${t(p)}</p></article>`).join('')}</div></section>
 <section class="section section-dark" data-moose-mood="curious"><div class="wrap industries-layout"><div>${heading(ctx,'Built around your world','Different businesses. One thoughtful approach.')}<p>${t('Your customers and your process come first.')}</p>${link('Explore industries','industries',ctx)}</div>${industryCards(ctx)}</div></section>${process(ctx)}
 <section class="section section-tint"><div class="wrap">${heading(ctx,'A clear starting point','Start with what you need.','Considered solutions. Approachable starting prices.')}${priceJourney(ctx)}</div></section>
 <section class="section wrap about-teaser"><p class="eyebrow">${t('A practical technology partner')}</p><h2>${t('Good technology should make business feel simpler.')}</h2><div><p>${t('MooseTVs brings AI, software and web development together. We start with your goals and build something useful, clear and ready to grow.')}</p>${link('About MooseTVs','about',ctx)}</div></section>${cta(ctx)}`;
}
