import {esc, icon as oldIcon} from '../components.mjs';
export {esc};
export const email='moosetvs1@gmail.com';
export const languages={en:'English',he:'עברית',ar:'العربية'};
export const href=(path='',lang='en')=>{if(path==='404')return `${lang==='en'?'':`/${lang}`}/404.html`;const [route,query]=path.split('?');return `${lang==='en'?'':`/${lang}`}/${route.replace(/^\/+|\/+$/g,'')}${route?'/':''}${query?'?'+query:''}`;};
export function icon(name){
  const paths={arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',coffee:'<path d="M4 5h12v9a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5V5Zm12 1h2a3 3 0 0 1 0 6h-2M3 22h15"/>',activity:'<path d="M2 12h5l3-9 4 18 3-9h5"/>',home:'<path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-8h6v8"/>',car:'<path d="m5 8 2-5h10l2 5M3 8h18v10H3V8Zm2 10v3m14-3v3M6 13h2m8 0h2"/>',shop:'<path d="M3 10h18l-2-7H5l-2 7Zm2 0v11h14V10M9 21v-7h6v7"/>',briefcase:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12l9 3 9-3M12 12v5"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',lock:'<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/>'};
  return paths[name]?`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`:oldIcon(name);
}
export const link=(label,path,ctx,cls='text-link')=>`<a class="${cls}" href="${href(path,ctx.lang)}">${ctx.t(label)}${icon('arrow')}</a>`;
export const brand=lang=>`<a class="brand" href="${href('',lang)}" aria-label="MooseTVs" dir="ltr"><span class="brand-symbol" aria-hidden="true">m<span>•</span></span>MooseTVs<span class="brand-period">.</span></a>`;
export function languageSelect(ctx,id){return `<label class="language-control"><span class="sr-only">${ctx.t('Language')}</span>${icon('globe')}<select id="${id}" data-language aria-label="${ctx.t('Language')}">${Object.entries(languages).map(([code,name])=>`<option value="${code}"${code===ctx.lang?' selected':''}>${name}</option>`).join('')}</select></label>`;}
export function header(ctx,path){return `<a class="skip" href="#main">${ctx.t('Skip to content')}</a><header class="site-header"><div class="wrap nav-wrap">${brand(ctx.lang)}<nav id="navigation" class="main-nav" aria-label="${ctx.t('Main navigation')}">${['Services','Work','Industries','Pricing','About','Contact'].map(n=>`<a href="${href(n.toLowerCase(),ctx.lang)}"${path.split('/')[0]===n.toLowerCase()?' aria-current="page"':''}>${ctx.t(n)}</a>`).join('')}<a class="mobile-signin" href="${href('sign-in',ctx.lang)}" data-account-link>${ctx.t('Sign In')}</a></nav><div class="nav-actions">${languageSelect(ctx,'header-language')}<a class="signin-link" href="${href('sign-in',ctx.lang)}" data-account-link>${ctx.t('Sign In')}</a>${link('Get a Quote','quote',ctx,'button small')}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation" aria-label="${ctx.t('Menu')}"><span></span><span></span></button></div></div></header>`;}
export function footer(ctx){return `<footer class="site-footer"><div class="wrap footer-grid"><div>${brand(ctx.lang)}<p class="footer-tagline">${ctx.t('Thoughtful technology.')}<br>${ctx.t('Built for your next chapter.')}</p><a href="mailto:${email}" dir="ltr">${email}</a></div><div><h2>${ctx.t('Explore')}</h2>${['Services','Work','Industries','Pricing'].map(x=>link(x,x.toLowerCase(),ctx,'footer-link')).join('')}</div><div><h2>${ctx.t('Company')}</h2>${['About','Contact','Privacy','Terms'].map(x=>link(x,x.toLowerCase(),ctx,'footer-link')).join('')}</div><div><h2>${ctx.t('Stay connected')}</h2><span class="social-placeholder">LinkedIn · Instagram<br><small>${ctx.t('Coming soon')}</small></span>${languageSelect(ctx,'footer-language')}</div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} MooseTVs</span><span>${ctx.t('Build. Automate. Grow.')}</span><a href="https://moosetvs.com" dir="ltr">moosetvs.com ${icon('arrow')}</a></div></footer>`;}
export const heading=(ctx,eyebrow,title,description='',extra='')=>`<div class="section-heading"><div><p class="eyebrow">${ctx.t(eyebrow)}</p><h2>${ctx.t(title)}</h2>${description?`<p>${ctx.t(description)}</p>`:''}</div>${extra}</div>`;
export const pageHero=(ctx,eyebrow,title,description)=>`<section class="page-intro wrap"><p class="eyebrow">${ctx.t(eyebrow)}</p><h1>${ctx.t(title)}</h1><p class="intro-copy">${ctx.t(description)}</p></section>`;
export const cta=ctx=>`<section class="cta-band"><div class="wrap"><div><p class="eyebrow">${ctx.t('Your next chapter')}</p><h2>${ctx.t('Something better starts here.')}</h2><p>${ctx.t('Tell us what you have in mind. We’ll help shape the next step.')}</p></div>${link('Start a Project','quote',ctx,'button')}</div></section>`;
