import {icon} from './layout.mjs';

// Small, native vector/HTML scenes: no video, remote animation library or canvas.
export function serviceIllustration(slug){
 if(slug==='ai-automation')return `<div class="service-scene robot-scene" data-motion-scene="robot" aria-hidden="true"><div class="robot-chat chat-in"><span></span><span></span></div><svg viewBox="0 0 220 110" class="service-robot" fill="none"><g class="robot-wave"><path d="M143 65q29 0 30-26" stroke="currentColor" stroke-width="9" stroke-linecap="round"/><circle cx="173" cy="34" r="9" class="robot-hand"/></g><path d="M79 65q-21 1-23 18" stroke="currentColor" stroke-width="9" stroke-linecap="round"/><rect x="81" y="64" width="57" height="37" rx="15" class="robot-body"/><path d="M110 22V11" stroke="currentColor" stroke-width="3"/><circle cx="110" cy="9" r="4" class="robot-antenna"/><rect x="69" y="23" width="82" height="50" rx="19" class="robot-head"/><rect x="81" y="34" width="58" height="26" rx="10" class="robot-face"/><g class="robot-eyes"><path d="M95 44v7m30-7v7" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></g><path d="M106 53q4 4 8 0" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><circle cx="110" cy="84" r="4" class="robot-light"/></svg><div class="robot-chat chat-out">${icon('check')}</div></div>`;
 if(slug==='web-development')return `<div class="service-scene web-scene" data-motion-scene="website" aria-hidden="true"><div class="build-browser"><div class="build-browser-bar"><i></i><i></i><i></i><span></span></div><div class="build-browser-page"><div class="build-web-copy"><i></i><i></i><b></b></div><div class="build-web-picture"></div><div class="build-web-tile"></div><div class="build-web-tile"></div><div class="build-web-tile"></div></div></div><div class="build-pointer">${icon('arrow')}</div></div>`;
 if(slug==='custom-software')return `<div class="service-scene software-scene" data-motion-scene="software" aria-hidden="true"><span class="software-brace">{</span><div class="software-modules"><div>${icon('user')}<span></span><i></i></div><div>${icon('grid')}<span></span><i></i></div><div>${icon('flow')}<span></span><i></i></div></div><span class="software-brace">}</span><span class="software-ready">${icon('check')}</span></div>`;
 return `<div class="service-scene products-scene" data-motion-scene="products" aria-hidden="true"><div class="product-sheet sheet-back"></div><div class="product-sheet sheet-middle"></div><div class="product-sheet sheet-front"><div>${icon('box')}</div><i></i><i></i><span></span></div><div class="product-download">${icon('arrow')}</div></div>`;
}

export function newProjectVisual(kind,ctx){
 const t=ctx.t;
 if(kind==='spaces')return `<div class="project-art spaces-art" aria-hidden="true"><div class="space-card"><div class="space-card-top"><span>FORMA / 04</span><span>${t('Explore a space')}</span></div><div class="floorplan"><div class="plan-living"><span>${t('Living')}</span><i class="plan-sofa"></i><i class="plan-table"></i></div><div class="plan-bedroom"><span>${t('Bedroom')}</span><i class="plan-bed"></i></div><div class="plan-terrace"><span>${t('Terrace')}</span><i></i><i></i></div><span class="plan-marker"></span></div><div class="space-details"><span>02 <small>${t('Bedrooms')}</small></span><span>86 <small>m²</small></span><b>↗</b></div></div><span class="art-caption">${t('Spatial experience concept')}</span></div>`;
 if(kind==='voice')return `<div class="project-art voice-art" aria-hidden="true"><div class="voice-card"><div class="voice-heading">${icon('chat')}<span>${t('A little help, hands-free.')}</span></div><div class="voice-wave">${[13,24,38,58,78,47,65,91,56,76,49,31,48,24,14].map(h=>`<i class="voice-bar"></i>`).join('')}</div><div class="voice-transcript"><span>${t('Find a time that works for me.')}</span><span>${icon('check')}${t('Here are your next available options.')}</span></div><div class="voice-footer"><span class="voice-dot"></span>${t('Voice interface concept')}</div></div></div>`;
 if(kind==='fulfilment')return `<div class="project-art fulfilment-art" aria-hidden="true"><div class="dispatch-card"><div class="dispatch-heading"><span>FIELDNOTES / STUDIO</span>${icon('box')}</div><div class="dispatch-package"><div class="package-top"></div><div class="package-face"><span>f.</span><i></i><small>#0248</small></div></div><div class="dispatch-route"><span class="dispatch-stop">${icon('check')}<small>${t('Picked')}</small></span><i></i><span class="dispatch-stop">${icon('check')}<small>${t('Packed')}</small></span><i></i><span class="dispatch-stop last">${icon('arrow')}<small>${t('On its way')}</small></span></div></div><span class="art-caption">${t('Fulfilment experience concept')}</span></div>`;
 return null;
}
