import {href,icon,link,heading,pageHero,cta,email,esc} from './layout.mjs';
import {projects,services,industries,problems} from './data.mjs';
import {serviceCards,visual,projectCards,industryCards,process,priceCards} from './sections.mjs';
import {leadForm,contactAside} from './forms.mjs';
import {accountPages} from './account-pages.mjs';
export function sitePages(ctx){
 const t=ctx.t, pages=[];
 const add=(path,title,description,body,extra={})=>pages.push({path,title:ctx.text(title),description:ctx.text(description),body,...extra});
 add('','Technology for a better business','Custom AI automation, websites and software. Thoughtful technology for modern businesses.',`<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span>${t('Thoughtful technology. Real possibility.')}</p><h1>${t('Build smarter.')}<br>${t('Automate more.')}<br><em>${t('Grow faster.')}</em></h1><p class="hero-description">${t('We build AI automations, websites and custom software for modern businesses.')}</p><div class="button-row">${link('Get a Quote','quote',ctx,'button')}${link('View Our Work','work',ctx,'button outline-light')}</div><p class="hero-footnote"><span></span>${t('Built around your business. Designed for what’s next.')}</p></div><div class="hero-visual">${visual('dashboard',ctx,true)}<div class="visual-caption"><span>01 — ${t('THE CONNECTED BUSINESS')}</span><span>${t('Interface concept')}</span></div></div></div><div class="wrap hero-bottom"><span>${t('From the first idea to the everyday details.')}</span><span>${t('AI. Websites. Software. Possibility.')}</span></div></section><section class="section wrap">${heading(ctx,'Our expertise','Better tools. Bigger possibilities.','Four ways to move your business forward.',link('Explore services','services',ctx))}${serviceCards(ctx)}</section><section class="section section-tint"><div class="wrap">${heading(ctx,'Selected concepts','A glimpse of what’s possible.','Ideas made tangible. Explore the experiences we can build.',link('View all work','work',ctx))}${projectCards(ctx,projects.filter(p=>p.featured))}<p class="section-note">${t('Concept projects with sample data. Real client work will be added here.')}</p></div></section><section class="section wrap">${heading(ctx,'Less friction. More focus.','Make room for the work that matters.')}<div class="problems-grid">${problems.map(([i,h,p])=>`<article>${icon(i)}<h3>${t(h)}</h3><p>${t(p)}</p></article>`).join('')}</div></section><section class="section section-dark"><div class="wrap industries-layout"><div>${heading(ctx,'Built around your world','Different businesses. One thoughtful approach.')}<p>${t('Your customers and your process come first.')}</p>${link('Explore industries','industries',ctx)}</div>${industryCards(ctx)}</div></section>${process(ctx)}<section class="section section-tint"><div class="wrap">${heading(ctx,'A clear starting point','Start with what you need.','Considered solutions. Approachable starting prices.',link('View pricing','pricing',ctx))}${priceCards(ctx)}</div></section><section class="section wrap about-teaser"><p class="eyebrow">${t('A practical technology partner')}</p><h2>${t('Good technology should make business feel simpler.')}</h2><div><p>${t('MooseTVs brings AI, software and web development together. We start with your goals and build something useful, clear and ready to grow.')}</p>${link('About MooseTVs','about',ctx)}</div></section>${cta(ctx)}`);
 add('services','Services','Explore AI automation, web development, custom software and digital products.',pageHero(ctx,'Our expertise','Built for better business.','From your customer-facing website to the systems behind it.')+`<section class="section wrap section-first">${serviceCards(ctx)}</section>`+process(ctx)+cta(ctx));
 for(const s of services) add(`services/${s.slug}`,s.name,s.intro,pageHero(ctx,s.name,s.headline,s.intro)+`<section class="section wrap section-first"><div class="benefit-strip">${s.benefits.map(b=>`<span>${icon('check')}${t(b)}</span>`).join('')}</div>${heading(ctx,'What we build','Useful by design.')}<div class="build-grid">${s.builds.map((b,i)=>`<article><span>0${i+1}</span><h3>${t(b)}</h3></article>`).join('')}</div><div class="example-callout"><span class="eyebrow">${t('In practice')}</span><p>${t(s.example)}</p></div></section><section class="section section-tint"><div class="wrap">${heading(ctx,'Explore the idea','See what it could look like.')}${projectCards(ctx,projects.filter(p=>p.slug===s.project))}</div></section>`+process(ctx)+cta(ctx));
 // Keep the established digital-products URL; canonical points to the new service route.
 const digital=pages.find(p=>p.path==='services/digital-products');pages.push({...digital,path:'digital-products',canonical:'services/digital-products',noindex:true});
 add('work','Work & concepts','Explore MooseTVs website, automation and business software concepts.',pageHero(ctx,'The work','Ideas, brought to life.','A growing collection of websites, workflows and software experiences.')+`<section class="section wrap section-first"><div class="work-toolbar"><p>${t('Concept projects. Real possibilities.')}</p><div class="work-filters" role="group" aria-label="${t('Filter projects')}">${['All',...new Set(projects.map(p=>p.category))].map((c,i)=>`<button type="button" data-filter="${c}" aria-pressed="${i===0}">${t(c)}</button>`).join('')}</div></div>${projectCards(ctx)}<p class="section-note">${t('Concept projects with sample data. Real client work will be added here.')}</p></section>`+cta(ctx));
 for(const p of projects)add(`work/${p.slug}`,p.title,p.shortDescription,pageHero(ctx,p.category,p.title,p.shortDescription)+`<section class="wrap project-detail section-first"><div class="project-showcase">${p.screenshots.length?`<img src="${esc(p.screenshots[0].src)}" alt="${t(p.screenshots[0].alt)}" width="1200" height="800">`:visual(p.visual,ctx)}</div><div class="project-story"><div><p class="eyebrow">${t(p.status)} · ${p.year}</p><h2>${t('The idea')}</h2><p>${t(p.fullDescription)}</p><p class="form-note">${t('Placeholder portfolio entry. This is not a paid client case study.')}</p><div class="button-row">${p.demoUrl?`<a class="button" href="${esc(href(p.demoUrl,ctx.lang))}">${t('Explore the demo')}${icon('arrow')}</a>`:''}${p.githubUrl?`<a class="button secondary" href="${esc(p.githubUrl)}" rel="noopener noreferrer">GitHub${icon('arrow')}</a>`:''}${link('All work','work',ctx,'text-link')}</div></div><aside><h3>${t('Built with')}</h3><div class="technology-list">${p.technologies.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>${t('Status')}</h3><p>${t(p.status)}</p></aside></div>${p.screenshots.slice(1).map(s=>`<img class="project-screenshot" src="${esc(s.src)}" alt="${t(s.alt)}" width="1200" height="800" loading="lazy">`).join('')}</section>`+cta(ctx));
 add('industries','Industries','Practical technology for restaurants, gyms, salons, clinics and other businesses.',pageHero(ctx,'Your world, our starting point','Built around your business.','Useful technology begins with understanding how you work.')+`<section class="section wrap section-first">${industryCards(ctx,true)}</section>`+cta(ctx));
 for(const [slug,name,desc] of industries)add(`industries/${slug}`,name,desc,pageHero(ctx,name,'Your business. A better way.',desc)+`<section class="section wrap section-first">${serviceCards(ctx)}<p class="section-note">${t('We define your requirements, data access and integrations before building.')}</p></section>`+cta(ctx));
 add('pricing','Pricing','Websites from $299, AI automation from $349 and flexible support plans.',pageHero(ctx,'Clear starting points','Good work. A clear investment.','Choose a starting point. We’ll shape the right scope together.')+`<section class="section wrap section-first">${priceCards(ctx)}<div class="pricing-faq"><details><summary>${t('What do starting prices include?')}</summary><p>${t('Each package covers a focused scope. Content, integrations, hosting and third-party subscriptions are confirmed in your proposal.')}</p></details><details><summary>${t('Can we start small?')}</summary><p>${t('Yes. Start with one useful website or workflow and expand when you need to.')}</p></details><details><summary>${t('What happens after launch?')}</summary><p>${t('You receive a clear handover. Ongoing maintenance and automation support are available as separate monthly plans.')}</p></details></div></section>`+cta(ctx));
 add('about','About MooseTVs','MooseTVs builds thoughtful AI, software and websites for real business needs.',pageHero(ctx,'About MooseTVs','Technology with a purpose.','We build custom AI, software and websites that make everyday business work better.')+`<section class="section wrap section-first about-layout"><div class="about-brand" aria-hidden="true">m<span>.</span><small>BUILD. AUTOMATE. GROW.</small></div><div><p class="eyebrow">${t('Your practical technology partner')}</p><h2>${t('Clear thinking. Considered execution.')}</h2><p>${t('MooseTVs brings AI, software and web development together. We start with your goals and build something useful, clear and ready to grow.')}</p><ul class="values-list">${['Business needs before technology choices','Direct communication and a clear scope','Careful testing and practical handover'].map(x=>`<li>${icon('check')}${t(x)}</li>`).join('')}</ul></div></section>`+cta(ctx));
 for(const q of [true,false])add(q?'quote':'contact',q?'Get a Quote':'Contact',q?'Tell us about your next website, automation or software project.':'Contact MooseTVs to discuss your business and your next idea.',pageHero(ctx,q?'Your next chapter':'Get in touch',q?'Let’s build something useful.':'Good things start with hello.','Tell us what you have in mind. We’ll help shape the next step.')+`<section class="section wrap section-first contact-layout">${leadForm(ctx,q)}${contactAside(ctx)}</section>`);
 add('thank-you','Thank you','Your next step with MooseTVs.',pageHero(ctx,'Thank you','A good start.','If you arrived after submitting an enquiry, we’ll review the details and get back to you.')+`<section class="section wrap section-first">${link('Back to home','',ctx,'button')}<p class="section-note">${t('Prefer a direct conversation?')} <a href="mailto:${email}">${email}</a></p></section>`,{noindex:true});
 add('privacy','Privacy','How MooseTVs uses enquiry and account information.',pageHero(ctx,'Privacy notice','Your information, handled with care.','A clear view of the information this website uses.')+`<article class="wrap legal"><h2>${t('Enquiries')}</h2><p>${t('We use the details you submit to respond and prepare proposals. Netlify processes forms and Gmail handles email conversations. Please avoid sensitive information.')}</p><h2>${t('Accounts')}</h2><p>${t('Supabase manages signup, login, password recovery and sessions. Your email and optional name identify your account. Passwords are handled by the authentication provider, never stored in this website’s source.')}</p><h2>${t('Browser storage')}</h2><p>${t('We remember your language and authentication session in browser storage. Campaign parameters may be stored for your current tab and included with an enquiry. We do not install advertising cookies.')}</p><h2>${t('Demo projects')}</h2><p>${t('Demos use fictional data. Details entered into a demo stay in page memory and disappear when you reload. Demo actions do not contact a real business.')}</p><h2>${t('Your choices')}</h2><p>${t('To request access, correction or deletion of your information, email us. We retain enquiries as needed for the conversation, resulting project and applicable record keeping.')}</p><a href="mailto:${email}">${email}</a></article>`);
 add('terms','Terms','Website use, concept projects and starting prices at MooseTVs.',pageHero(ctx,'Website terms','A clear starting point.','A separate written agreement defines every paid project.')+`<article class="wrap legal"><h2>${t('Services and prices')}</h2><p>${t('Prices are indicative starting points in USD. Scope, taxes, currency, third-party costs, timelines, ownership and support are agreed in a written proposal. Shekel values are illustrative estimates.')}</p><h2>${t('Concept projects')}</h2><p>${t('Portfolio concepts use fictional businesses and sample data. They do not represent real clients, performance claims or live transactions.')}</p><h2>${t('Accounts and responsible use')}</h2><p>${t('Use accurate account details, keep your password private and use this site for legitimate purposes. Future account features are placeholders until explicitly released.')}</p><h2>${t('Digital products')}</h2><p>${t('The free business starter uses the included MIT license. Review and customize it before publishing. Future SaaS products and paid subscriptions are not available yet.')}</p><h2>${t('Contact')}</h2><a href="mailto:${email}">${email}</a></article>`);
 add('404','Page not found','Find your way back to MooseTVs.',pageHero(ctx,'404','Let’s get you back on track.','That page isn’t here. Your next idea still has a home.')+`<section class="section wrap section-first">${link('Back to home','',ctx,'button')}</section>`,{noindex:true});
 return [...pages,...accountPages(ctx)];
}
