// English keys, with complete Hebrew and Arabic copy for the real-work showcase.
const rows=[
 ['Featured project showcase','תצוגת פרויקטים נבחרים','عرض المشاريع المختارة'],
 ['Explore project','לגלות את הפרויקט','اكتشف المشروع'],
 ['View all projects','לכל הפרויקטים','عرض جميع المشاريع'],
 ['Choose a project','בחירת פרויקט','اختر مشروعًا'],
 ['Show project','הצגת פרויקט','عرض المشروع'],
 ['Previous project','הפרויקט הקודם','المشروع السابق'],
 ['Next project','הפרויקט הבא','المشروع التالي'],
 ['Pause showcase','עצירת התצוגה','إيقاف العرض مؤقتًا'],
 ['Play showcase','הפעלת התצוגה','تشغيل العرض'],
 ['Automation, set in motion.','אוטומציה בתנועה.','الأتمتة في حركة.'],
 ['Twelve minds. One research flow.','שנים-עשר מוחות. תהליך מחקר אחד.','اثنا عشر عقلًا. مسار بحث واحد.'],
 ['Animated bot, moving data dots and illustrative market candles.','בוט מונפש, נקודות נתונים בתנועה ונרות שוק להמחשה.','بوت متحرك ونقاط بيانات متدفقة وشموع سوق توضيحية.'],
 ['Twelve connected research roles exchange information around a shared workspace.','שנים-עשר תפקידי מחקר מחוברים מחליפים מידע בסביבת עבודה משותפת.','اثنا عشر دورًا بحثيًا مترابطًا يتبادلون المعلومات في مساحة عمل مشتركة.'],
 ['A running athlete, moving sports typography and the actual ReeMove welcome screen.','ספורטאי רץ, כיתוב ספורטיבי בתנועה ומסך הפתיחה האמיתי של ReeMove.','رياضي يركض وكلمات رياضية متحركة وشاشة الترحيب الفعلية لتطبيق ReeMove.'],
 ['Sunlight travels across an illustrative solar array and energy flows toward a home.','אור שמש נע על מערך סולארי להמחשה ואנרגיה זורמת לעבר בית.','ضوء الشمس يعبر منظومة شمسية توضيحية والطاقة تتدفق نحو منزل.'],
 ['Animated project illustration','המחשה מונפשת של הפרויקט','رسم متحرك توضيحي للمشروع'],
 ['App interface + motion design','ממשק האפליקציה + עיצוב בתנועה','واجهة التطبيق + تصميم متحرك'],
 ['Paper research','מחקר בסימולציה','بحث بالمحاكاة'],
 ['AGENTS','סוכנים','وكلاء'],
 ['Move.','זזים.','تحرّك.'],['Connect.','מתחברים.','تواصل.'],['Grow.','צומחים.','تطوّر.'],
 ['Technical Analyst','אנליסט טכני','محلل فني'],
 ['Price Action Analyst','אנליסט פעולת מחיר','محلل حركة السعر'],
 ['Macro Analyst','אנליסט מאקרו','محلل الاقتصاد الكلي'],
 ['News Analyst','אנליסט חדשות','محلل الأخبار'],
 ['Sentiment Analyst','אנליסט סנטימנט','محلل المعنويات'],
 ['Bull Researcher','חוקר מגמה שורית','باحث الاتجاه الصعودي'],
 ['Bear Researcher','חוקר מגמה דובית','باحث الاتجاه الهبوطي'],
 ['Research Manager','מנהל מחקר','مدير البحث'],
 ['Aggressive Risk','סקירת סיכון אגרסיבית','مراجعة مخاطر جريئة'],
 ['Conservative Risk','סקירת סיכון שמרנית','مراجعة مخاطر متحفظة'],
 ['Neutral Risk','סקירת סיכון ניטרלית','مراجعة مخاطر محايدة'],
 ['Final Manager','מנהל מסכם','المدير النهائي'],
 ['Moose Engine','Moose Engine','Moose Engine'],['Aurum','Aurum','Aurum'],['ReeMove','ReeMove','ReeMove'],['Saleh Solar System','Saleh Solar System','Saleh Solar System'],
 ['Selected work','פרויקטים נבחרים','أعمال مختارة'],
 ['A glimpse of what we’ve built.','הצצה למה שכבר בנינו.','لمحة عمّا بنيناه.'],
 ['From specialist automation to immersive websites. Explore our projects.','מאוטומציה ייעודית ועד אתרים חווייתיים. הכירו את הפרויקטים שלנו.','من الأتمتة المتخصصة إلى المواقع التفاعلية. اكتشف مشاريعنا.'],
 ['Four projects. Different challenges. The same care for the details.','ארבעה פרויקטים. אתגרים שונים. אותה תשומת לב לפרטים.','أربعة مشاريع. تحديات مختلفة. والاهتمام نفسه بالتفاصيل.'],
 ['Our work','העבודות שלנו','أعمالنا'],
 ['Explore Moose Engine, Aurum, ReeMove and Saleh Solar System.','הכירו את Moose Engine, Aurum, ReeMove ו-Saleh Solar System.','اكتشف Moose Engine وAurum وReeMove وSaleh Solar System.'],
 ['Explore by discipline.','גלו לפי תחום.','تصفّح حسب المجال.'],
 ['The ideas lab','מעבדת הרעיונות','مختبر الأفكار'],
 ['More possibilities to explore.','עוד אפשרויות לגלות.','المزيد من الإمكانيات لتكتشفها.'],
 ['Interactive concepts with fictional businesses and sample data.','קונספטים אינטראקטיביים עם עסקים בדיוניים ונתוני הדגמה.','تصوّرات تفاعلية بأعمال خيالية وبيانات تجريبية.'],
 ['Mobile App','אפליקציה לנייד','تطبيق جوّال'],
 ['Custom-built bot','בוט בפיתוח מותאם','بوت مطوّر حسب الطلب'],
 ['Built application','אפליקציה שנבנתה','تطبيق مطوّر'],
 ['App in development','אפליקציה בפיתוח','تطبيق قيد التطوير'],
 ['Live website','אתר פעיל','موقع منشور'],
 ['The project','הפרויקט','المشروع'],
 ['Visit live website','לצפייה באתר הפעיל','زيارة الموقع'],
 ['opens in a new tab','נפתח בלשונית חדשה','يفتح في علامة تبويب جديدة'],
 ['Build something like this','בואו נבנה משהו כזה','لنبنِ شيئًا كهذا'],
 ['Project gallery','גלריית הפרויקט','معرض المشروع'],
 ['A closer look','מבט מקרוב','نظرة أقرب'],
 ['Inside the idea.','בתוך הרעיון.','داخل الفكرة.'],
 ['The details make the difference.','הפרטים שעושים את ההבדל.','التفاصيل تصنع الفرق.'],
 ['Open full image','פתיחת התמונה המלאה','فتح الصورة كاملة'],
 ['Project illustration','איור המחשה לפרויקט','رسم توضيحي للمشروع'],
 ['Move together. Grow stronger.','זזים יחד. מתחזקים יחד.','نتحرّك معًا. نصبح أقوى.'],
 ['An experience, not just a website.','חוויה, לא רק אתר.','تجربة، وليست مجرد موقع.'],
 ['Research, thoughtfully connected.','מחקר, מחובר במחשבה.','بحث مترابط بعناية.'],
 ['A custom MQL5 trading bot, built for MetaTrader 5.','בוט מסחר מותאם ב-MQL5, שנבנה עבור MetaTrader 5.','بوت تداول مخصّص بلغة MQL5، مطوّر لمنصة MetaTrader 5.'],
 ['Moose Engine is the portfolio name for our custom MQL5 / MetaTrader 5 bot project. It brings a trading workflow into software inside the trading terminal—a focused example of specialist automation development.','Moose Engine הוא השם שנבחר לתיק העבודות של פרויקט הבוט שלנו ב-MQL5 / MetaTrader 5. הוא הופך תהליך מסחר לתוכנה בתוך מסוף המסחר — דוגמה ממוקדת לפיתוח אוטומציה ייעודית.','Moose Engine هو الاسم الذي اخترناه لعرض مشروع بوت MQL5 / MetaTrader 5 في أعمالنا. يحوّل سير عمل التداول إلى برنامج داخل المنصة، كمثال على تطوير الأتمتة المتخصصة.'],
 ['Native MQL5 development','פיתוח ייעודי ב-MQL5','تطوير أصلي بلغة MQL5'],
 ['MetaTrader 5 environment','סביבת MetaTrader 5','بيئة MetaTrader 5'],
 ['Specialist automation','אוטומציה ייעודית','أتمتة متخصصة'],
 ['Engineering showcase only. The artwork is an illustration, not a terminal screenshot or verified trading result. Trading involves risk; no returns are promised.','הצגת יכולות פיתוח בלבד. הגרפיקה היא איור המחשה, לא צילום של מסוף מסחר או תוצאה מאומתת. מסחר כרוך בסיכון; אין הבטחה לתשואה.','عرض هندسي فقط. الصورة رسم توضيحي وليست لقطة لمنصة التداول أو نتيجة موثّقة. التداول ينطوي على مخاطر، ولا توجد وعود بالعوائد.'],
 ['Moose Engine illustration connecting MQL5 development to a MetaTrader 5 bot','איור Moose Engine המחבר פיתוח MQL5 לבוט MetaTrader 5','رسم Moose Engine يربط تطوير MQL5 ببوت MetaTrader 5'],
 ['Original project illustration · not a trading-results screenshot','איור מקורי לפרויקט · אינו צילום של תוצאות מסחר','رسم أصلي للمشروع · ليس لقطة لنتائج تداول'],
 ['Twelve research perspectives. One beautifully organized workspace.','שתים-עשרה נקודות מבט מחקריות. סביבת עבודה אחת מסודרת להפליא.','اثنتا عشرة زاوية بحثية. مساحة عمل واحدة منظّمة بعناية.'],
 ['Aurum is a multi-market paper-research application adapted from TradingAgents. Specialist analysts, opposing research views and risk reviewers feed a recorded decision. A custom dashboard brings the agent room, signal history and deterministic outcome tracking together.','Aurum היא אפליקציית מחקר וסימולציה למספר שווקים, המבוססת על התאמה של TradingAgents. אנליסטים ייעודיים, עמדות מחקר מנוגדות ובוחני סיכון תורמים להחלטה מתועדת. לוח בקרה מותאם מחבר בין חדר הסוכנים, היסטוריית האותות ומעקב תוצאות לפי כללים קבועים.','Aurum تطبيق بحث ومحاكاة لأسواق متعددة، مبني بتكييف TradingAgents. يشارك محللون متخصصون وباحثون بوجهات نظر متعارضة ومراجعو مخاطر في قرار موثّق. تجمع لوحة مخصّصة غرفة الوكلاء وسجل الإشارات وتتبع النتائج بقواعد محدّدة.'],
 ['Twelve-role research workflow','תהליך מחקר עם שנים-עשר תפקידים','سير بحث يضم اثني عشر دورًا'],
 ['Recorded evidence and decisions','תיעוד ראיות והחלטות','أدلة وقرارات موثّقة'],
 ['Multi-market dashboard and reports','לוח בקרה ודוחות למספר שווקים','لوحة وتقارير لأسواق متعددة'],
 ['Paper research only: no broker connection or real-money execution. These genuine interface captures use an isolated, empty workspace with integrations disabled. They do not show investment performance. Built on the open-source TradingAgents project.','מחקר בסימולציה בלבד: ללא חיבור לברוקר או ביצוע בכסף אמיתי. צילומי הממשק האמיתיים נלקחו מסביבת עבודה מבודדת וריקה, עם חיבורים כבויים. הם אינם מציגים ביצועי השקעה. מבוסס על פרויקט הקוד הפתוח TradingAgents.','للبحث بالمحاكاة فقط: لا اتصال بوسيط ولا تنفيذ بأموال حقيقية. لقطات الواجهة الفعلية مأخوذة من مساحة عمل معزولة وفارغة مع تعطيل التكاملات. لا تعرض أداء استثماريًا. مبني على مشروع TradingAgents مفتوح المصدر.'],
 ['Aurum agent room showing specialist research roles','חדר הסוכנים של Aurum המציג תפקידי מחקר ייעודיים','غرفة وكلاء Aurum تعرض أدوار البحث المتخصصة'],
 ['The agent room · actual application, isolated portfolio workspace','חדר הסוכנים · האפליקציה האמיתית בסביבת תיק עבודות מבודדת','غرفة الوكلاء · التطبيق الفعلي في مساحة عرض معزولة'],
 ['Aurum overview with market selection and research navigation','סקירת Aurum עם בחירת שוק וניווט מחקר','نظرة عامة على Aurum مع اختيار الأسواق وتنقّل البحث'],
 ['The overview · actual application, integrations disabled','סקירה כללית · האפליקציה האמיתית, עם חיבורים כבויים','النظرة العامة · التطبيق الفعلي، مع تعطيل التكاملات'],
 ['A sports community built around how you move.','קהילת ספורט שבנויה סביב הדרך שלכם לזוז.','مجتمع رياضي مبني حول طريقتك في الحركة.'],
 ['ReeMove brings sports profiles, community content, nearby discovery, events, challenges and messaging into a Flutter application backed by Firebase. Its welcoming identity and cross-platform interface connect the product around one idea: move together, grow stronger.','ReeMove משלבת פרופילי ספורט, תוכן קהילתי, גילוי מקומות קרובים, אירועים, אתגרים והודעות באפליקציית Flutter עם Firebase. הזהות המזמינה והממשק למגוון פלטפורמות מחברים את המוצר סביב רעיון אחד: זזים יחד, מתחזקים יחד.','يجمع ReeMove الملفات الرياضية ومحتوى المجتمع والاكتشاف القريب والفعاليات والتحديات والمراسلة في تطبيق Flutter مدعوم بـFirebase. هويته المرحّبة وواجهته متعددة المنصات تتمحوران حول فكرة واحدة: نتحرّك معًا، ونصبح أقوى.'],
 ['Sports profiles and communities','פרופילי ספורט וקהילות','ملفات رياضية ومجتمعات'],
 ['Nearby discovery and events','גילוי מקומות ואירועים קרובים','اكتشاف الأماكن والفعاليات القريبة'],
 ['Messaging and activity features','הודעות ויכולות פעילות','المراسلة وميزات النشاط'],
 ['Application project in development, not an announced app-store release. Images show the actual welcome and account-creation interfaces. No customer account or private profile data is displayed.','פרויקט אפליקציה בפיתוח, ולא השקה מוכרזת בחנויות האפליקציות. התמונות מציגות את מסכי הפתיחה ויצירת החשבון האמיתיים. לא מוצגים פרטי חשבון לקוח או מידע פרטי.','مشروع تطبيق قيد التطوير، وليس إصدارًا معلنًا في متاجر التطبيقات. الصور تعرض واجهتَي الترحيب وإنشاء الحساب الفعليتين، دون عرض بيانات حسابات عملاء أو ملفات خاصة.'],
 ['ReeMove desktop welcome screen with green sports-community branding','מסך הפתיחה של ReeMove למחשב עם מיתוג קהילת ספורט ירוק','شاشة ترحيب ReeMove للحاسوب بهوية رياضية خضراء'],
 ['Actual ReeMove welcome screen','מסך הפתיחה האמיתי של ReeMove','شاشة الترحيب الفعلية لتطبيق ReeMove'],
 ['ReeMove mobile welcome screen','מסך הפתיחה של ReeMove בנייד','شاشة ترحيب ReeMove على الجوّال'],
 ['The mobile welcome experience','חוויית הפתיחה בנייד','تجربة الترحيب على الجوّال'],
 ['ReeMove mobile account-creation interface with empty fields','ממשק יצירת חשבון של ReeMove בנייד עם שדות ריקים','واجهة إنشاء حساب ReeMove على الجوّال بحقول فارغة'],
 ['Creating a sports identity · actual app interface','יצירת זהות ספורטיבית · ממשק האפליקציה האמיתי','إنشاء هوية رياضية · واجهة التطبيق الفعلية'],
 ['An interactive solar experience. Made to shine.','חוויית אנרגיה סולארית אינטראקטיבית. נבנתה כדי לזרוח.','تجربة طاقة شمسية تفاعلية. صُمّمت لتشرق.'],
 ['An immersive website for Saleh Solar System that turns a solar installation into an explorable 3D experience. Visitors adjust the daylight, switch between home and business arrays and look inside a panel. A multilingual content studio lets the owner publish photos and videos.','אתר חווייתי ל-Saleh Solar System שהופך מערכת סולארית לחוויית תלת-ממד שאפשר לחקור. המבקרים משנים את אור היום, עוברים בין מערכות לבית ולעסק ומציצים לתוך פאנל. סטודיו תוכן רב-לשוני מאפשר לבעלים לפרסם תמונות וסרטונים.','موقع غامر لـSaleh Solar System يحوّل منظومة الطاقة الشمسية إلى تجربة ثلاثية الأبعاد قابلة للاستكشاف. يتحكّم الزائر بضوء النهار، ويبدّل بين المنظومة المنزلية والتجارية، ويستكشف طبقات اللوح. يتيح استوديو محتوى متعدد اللغات للمالك نشر الصور والفيديو.'],
 ['Interactive 3D solar installation','מערכת סולארית אינטראקטיבית בתלת-ממד','منظومة شمسية تفاعلية ثلاثية الأبعاد'],
 ['English, Hebrew and Arabic','אנגלית, עברית וערבית','الإنجليزية والعبرية والعربية'],
 ['Owner-managed photo and video gallery','גלריית תמונות וסרטונים בניהול הבעלים','معرض صور وفيديو بإدارة المالك'],
 ['A live website built for Saleh Solar System. The daylight indicator is an illustrative interaction, not an energy-production estimate.','אתר פעיל שנבנה עבור Saleh Solar System. מדד אור היום הוא המחשה אינטראקטיבית ולא אומדן לייצור אנרגיה.','موقع منشور بُني لـSaleh Solar System. مؤشّر ضوء النهار تفاعل توضيحي، وليس تقديرًا لإنتاج الطاقة.'],
 ['Saleh Solar System homepage with a three-dimensional solar installation','עמוד הבית של Saleh Solar System עם מערכת סולארית תלת-ממדית','الصفحة الرئيسية لـSaleh Solar System بمنظومة شمسية ثلاثية الأبعاد'],
 ['The live homepage · a solar installation in 3D','עמוד הבית הפעיל · מערכת סולארית בתלת-ממד','الصفحة الرئيسية المنشورة · منظومة شمسية ثلاثية الأبعاد'],
 ['Exploded solar-panel view showing glass, cells and aluminum frame','מבט מפורק על פאנל סולארי המציג זכוכית, תאים ומסגרת אלומיניום','منظر تفكيكي للوح شمسي يُظهر الزجاج والخلايا وإطار الألومنيوم'],
 ['A closer look · exploring a panel layer by layer','מבט מקרוב · חוקרים פאנל שכבה אחר שכבה','نظرة أقرب · استكشاف اللوح طبقةً طبقةً']
];
export const portfolioMessages=Object.fromEntries(['en','he','ar'].map((lang,i)=>[lang,Object.fromEntries(rows.map(row=>[row[0],row[i]]))]));
