import {esc,href,icon,link,heading,pageHero,cta} from './layout.mjs';

export function projectMedia(ctx,p){
 const t=ctx.t, first=p.screenshots[0];
 if(p.visual==='reemove')return `<div class="work-cover cover-reemove" dir="ltr"><div class="cover-wordmark"><span>ReeMove</span><small>${t('Move together. Grow stronger.')}</small></div><div class="phone-pair">${p.screenshots.slice(1).map((s,i)=>`<div class="portfolio-phone phone-${i}"><img src="${esc(s.src)}" alt="${t(s.alt)}" width="390" height="844" loading="lazy"></div>`).join('')}</div><span class="cover-caption">FLUTTER / FIREBASE</span></div>`;
 if(p.visual==='engine')return `<div class="work-cover cover-engine"><img src="${esc(first.src)}" alt="${t(first.alt)}" width="1200" height="800" loading="lazy"><span class="cover-disclosure">${t('Project illustration')}</span></div>`;
 return `<div class="work-cover cover-${esc(p.visual)}" dir="ltr"><div class="cover-wordmark"><span>${esc(p.title)}</span><small>${t(p.visual==='solar'?'An experience, not just a website.':'Research, thoughtfully connected.')}</small></div><div class="portfolio-browser"><div class="portfolio-browser-bar" aria-hidden="true"><i></i><i></i><i></i><span>${p.visual==='solar'?'SALEH SOLAR SYSTEM':'AURUM / AGENT ROOM'}</span></div><img src="${esc(first.src)}" alt="${t(first.alt)}" width="1265" height="712" loading="lazy"></div></div>`;
}

export function realProjectPage(ctx,p){
 const t=ctx.t;
 return pageHero(ctx,p.category,p.title,p.shortDescription)+`<section class="wrap project-detail section-first real-project-detail"><div class="project-showcase">${projectMedia(ctx,p)}</div><div class="project-story"><div><p class="eyebrow">${t(p.status)} · ${p.year}</p><h2>${t('The project')}</h2><p>${t(p.fullDescription)}</p><div class="button-row">${p.liveUrl?`<a class="button" href="${esc(p.liveUrl)}" target="_blank" rel="noopener noreferrer">${t('Visit live website')}${icon('arrow')}<span class="sr-only"> (${t('opens in a new tab')})</span></a>`:''}${link('Build something like this','quote',ctx,p.liveUrl?'text-link':'button')}${link('All work','work',ctx,'text-link')}</div></div><aside><h3>${t('Built with')}</h3><div class="technology-list">${p.technologies.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>${t('Status')}</h3><p>${t(p.status)}</p></aside></div><div class="project-capabilities">${p.highlights.map((h,i)=>`<div><span>0${i+1}</span><h3>${t(h)}</h3></div>`).join('')}</div><section class="project-gallery" aria-label="${t('Project gallery')}">${heading(ctx,'A closer look',p.visual==='engine'?'Inside the idea.':'The details make the difference.')}<div class="project-gallery-grid">${p.screenshots.map(s=>`<figure class="project-figure${s.mobile?' is-mobile':''}"><a href="${esc(s.src)}" target="_blank" rel="noopener noreferrer" aria-label="${t('Open full image')}: ${t(s.alt)} (${t('opens in a new tab')})"><img src="${esc(s.src)}" alt="${t(s.alt)}" width="${s.mobile?390:p.visual==='engine'?1200:1265}" height="${s.mobile?844:p.visual==='engine'?800:712}" loading="lazy"></a><figcaption>${t(s.caption)} <span aria-hidden="true">↗</span></figcaption></figure>`).join('')}</div></section><div class="project-context"><span>${icon('info')}</span><p>${t(p.note)}</p></div></section>`+cta(ctx);
}
