import {icon,link,href,esc,heading} from './layout.mjs';
import {projects,services,industries,plans,steps} from './data.mjs';
import {serviceIllustration,newProjectVisual} from './motion-art.mjs';
import {validStage} from './valid.mjs';
import {projectMedia} from './portfolio.mjs';
export const serviceCards=ctx=>`<div class="service-grid">${services.map((s,i)=>`<article class="service-card service-card-animated"><div class="card-top">${icon(s.icon)}<span>0${i+1}</span></div>${serviceIllustration(s.slug)}<h3>${ctx.t(s.name)}</h3><p>${ctx.t(s.description)}</p>${link('Learn More',`services/${s.slug}`,ctx)}</article>`).join('')}</div>`;
export function visual(kind,ctx,large=false){
 const t=ctx.t;
 const fresh=newProjectVisual(kind,ctx);if(fresh)return fresh;
 if(kind==='restaurant'||kind==='website')return `<div class="project-art ${kind}" aria-hidden="true"><div class="mini-browser"><div class="browser-line"><span></span><span></span><span></span><small>${kind==='restaurant'?'olive & ember':'NORTHLINE'}</small></div><div class="mini-web"><span class="mini-kicker">${t(kind==='restaurant'?'Seasonal. Simple. Beautiful.':'A better place to begin.')}</span><strong>${t(kind==='restaurant'?'Good food.':'Thoughtful spaces.')}<br><em>${t(kind==='restaurant'?'Better company.':'Beautifully made.')}</em></strong><span class="mini-web-button">${t(kind==='restaurant'?'A seat at the table':'Explore the details')} ↗</span><div class="art-orb"></div><span class="art-caption">${t('Website concept')}</span></div></div></div>`;
 if(kind==='automation')return `<div class="project-art automation" aria-hidden="true"><div class="automation-nodes"><div class="node">${icon('mail')}<span>${t('New enquiry')}</span><i>01</i></div><div class="node-connector"></div><div class="node gold">${icon('spark')}<span>${t('Thoughtfully automated')}</span><i>02</i></div><div class="node-connector"></div><div class="node-branches"><div class="node">${icon('grid')}<span>${t('Organized')}</span></div><div class="node">${icon('check')}<span>${t('Ready for review')}</span></div></div></div><span class="art-caption">${t('Workflow concept')}</span></div>`;
 if(kind==='booking')return `<div class="project-art booking" aria-hidden="true"><div class="mini-browser"><div class="browser-line"><span></span><span></span><span></span><small>CEDAR STUDIO</small></div><div class="mini-calendar"><strong>${t('Make time for yourself.')}</strong><div class="calendar-grid">${Array.from({length:21},(_,i)=>`<span${i===11?' class="selected"':''}>${i+1}</span>`).join('')}</div><div class="calendar-times"><span>09:00</span><span>10:30</span><span>12:00</span></div></div></div></div>`;
 return `<div class="project-art dashboard ${large?'hero-art':''}" aria-hidden="true"><div class="workspace"><div class="workspace-sidebar"><span class="workspace-logo">m.</span>${['grid','flow','calendar','user'].map(i=>icon(i)).join('')}<span class="sidebar-bottom">${icon('shield')}</span></div><div class="workspace-main"><div class="workspace-top"><span>Moose<span class="dim"> / ${t('Workspace')}</span></span><span class="avatar">M</span></div><div class="workspace-title"><div><span class="mini-kicker">${t('A little more clarity')}</span><strong>${t('Your business. Connected.')}</strong></div><span class="live-dot"></span></div><div class="workspace-metrics"><div><span>${t('Enquiries')}</span><b>24<span>↗</span></b><small>${t('Sample data')}</small></div><div><span>${t('Workflows')}</span><b>08<span>↗</span></b><small>${t('In one place')}</small></div><div><span>${t('Your next step')}</span><b>03<span>↗</span></b><small>${t('Ready for review')}</small></div></div><div class="workspace-chart"><div><span>${t('A clearer picture')}</span><small>${t('Overview')}</small></div><svg viewBox="0 0 460 125" fill="none"><path class="chart-grid" d="M0 25h460M0 65h460M0 105h460"/><path class="chart-area" d="M0 103C30 103 35 78 65 78S110 90 145 62 173 92 213 66 235 72 278 43 322 73 354 41 390 50 417 24 443 35 460 10V125H0Z"/><path class="chart-line" d="M0 103C30 103 35 78 65 78S110 90 145 62 173 92 213 66 235 72 278 43 322 73 354 41 390 50 417 24 443 35 460 10"/></svg><div class="chart-labels"><span>01</span><span>07</span><span>14</span><span>21</span><span>28</span></div></div><div class="workspace-task">${icon('check')}<div><strong>${t('Less busywork. More possibility.')}</strong><span>${t('A concept of a better working day.')}</span></div><span>↗</span></div></div></div>${large?`<div class="floating-note">${icon('spark')}<div><strong>${t('Designed to work together')}</strong><span>${t('Your tools. One thoughtful system.')}</span></div></div>`:''}</div>`;
}
export function projectCards(ctx,items=projects){return `<div class="portfolio-grid${items.every(p=>p.kind==='real')?' real-work-grid':''}">${items.map(p=>`<article class="portfolio-card" data-project-category="${esc(p.category)}"><a class="project-image" href="${href(`work/${p.slug}`,ctx.lang)}" aria-label="${ctx.t('View Project')}: ${ctx.t(p.title)}">${p.kind==='real'?projectMedia(ctx,p):p.screenshots.length?`<img src="${esc(p.screenshots[0].src)}" alt="${ctx.t(p.screenshots[0].alt)}" width="800" height="600" loading="lazy">`:visual(p.visual,ctx)}<span class="project-open">↗</span></a><div class="project-info"><div class="project-meta"><span>${ctx.t(p.category)}</span><span>${ctx.t(p.status)}</span></div><h3>${ctx.t(p.title)}</h3><p>${ctx.t(p.shortDescription)}</p><div class="technology-list">${p.technologies.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${link('View Project',`work/${p.slug}`,ctx)}</div></article>`).join('')}</div>`;}
export const industryCards=(ctx,full=false)=>`<div class="industry-grid">${industries.map(([slug,name,desc,i])=>`<a href="${href(`industries/${slug}`,ctx.lang)}" class="industry-card">${icon(i)}<div><h3>${ctx.t(name)}</h3>${full?`<p>${ctx.t(desc)}</p>`:''}</div><span>↗</span></a>`).join('')}</div>`;
export const process=ctx=>`<section class="section wrap" data-process>${heading(ctx,'A considered process','Good work. Clear steps.')}${validStage(ctx,'process')}<ol class="process-grid">${steps.map(([name,desc],i)=>`<li data-process-detail="${i}"><span>0${i+1}</span><h3>${ctx.t(name)}</h3><p>${ctx.t(desc)}</p></li>`).join('')}</ol></section>`;
const rate=3.5; // Illustrative display rate, explicitly disclosed. Never presented as live FX.
export const money=(amount,ctx,monthly=false)=>`<div class="price"><span>${ctx.t('From')}</span><div><strong dir="ltr">$${amount}</strong>${monthly?`<small>${ctx.t('/month')}</small>`:''}</div><small class="ils" dir="auto">≈ <bdi>₪${Math.round(amount*rate).toLocaleString('en-US')}</bdi> ${ctx.t('SHEKELS')}${monthly?` ${ctx.t('/month')}`:''}</small></div>`;
export function priceCards(ctx){return `<div class="pricing-grid">${plans.map(p=>`<article class="pricing-card${p.featured?' featured':''}">${p.featured?`<span class="plan-badge">${ctx.t('Most popular')}</span>`:''}<h3>${ctx.t(p.name)}</h3><p>${ctx.t(p.description)}</p>${money(p.price,ctx)}<ul>${p.features.map(f=>`<li>${icon('check')}${ctx.t(f)}</li>`).join('')}</ul>${link('Get a Quote',`quote?plan=${encodeURIComponent(p.name)}`,ctx,'button '+(p.featured?'':'secondary'))}</article>`).join('')}</div><div class="support-strip"><div><strong>${ctx.t('Maintenance')}</strong><span><bdi>$25</bdi>${ctx.t('/month')} <small>≈ <bdi>₪88</bdi> ${ctx.t('SHEKELS')}</small></span></div><div><strong>${ctx.t('Managed Automation Support')}</strong><span><bdi>$89</bdi>${ctx.t('/month')} <small>≈ <bdi>₪312</bdi> ${ctx.t('SHEKELS')}</small></span></div><div><strong>${ctx.t('Custom Software')}</strong>${link('Request Quote','quote',ctx)}</div></div><p class="pricing-note">${ctx.t('Starting prices for a defined scope. Your proposal confirms deliverables and third-party costs.')} ${ctx.t('Shekel estimates use a display rate of $1 = ₪3.50, not a live exchange rate.')}</p>`;}
