import {link} from './layout.mjs';

// These are real spaces in the document, not a screen-edge widget. The optional
// WebGL character travels between their floor coordinates without blocking UI.
export function validStage(ctx,scene='hello'){
 const captions={hello:'A little personality. A lot of possibility.',expertise:'Four talents. One curious moose.',strong:'Small moose. Big possibilities.',process:'One thoughtful step at a time.',robot:'Less busywork. More human time.',web:'Let’s build your corner of the web.',binary:'Your ideas, translated into software.',package:'Good things, thoughtfully packaged.',pricing:'A clear starting point. Room to grow.'};
 return `<div class="valid-stage valid-stage-${scene}" data-valid-stage="${scene}" aria-hidden="true"><div class="valid-floor">${scene==='process'?Array.from({length:5},(_,i)=>`<i data-valid-step="${i}"><span>0${i+1}</span></i>`).join(''):'<span class="valid-floor-dot"></span><span class="valid-floor-line"></span>'}</div><span class="valid-stage-caption">${ctx.t(captions[scene]||captions.hello)}</span></div>`;
}
export function priceJourney(ctx){
 return `<div class="price-journey"><div class="price-journey-copy"><span class="eyebrow">${ctx.t('Room to grow')}</span><h3>${ctx.t('Start small. Think bigger.')}</h3><p>${ctx.t('From a focused first step to a connected business. Your scope sets the investment, not a one-size-fits-all package.')}</p>${link('Explore starting prices','pricing',ctx,'button')}<small>${ctx.t('Clear USD prices, with illustrative shekel estimates.')}</small></div><div class="valid-stage valid-stage-slide" data-valid-stage="slide" aria-hidden="true"><div class="range-grid"></div><svg class="valid-slide" viewBox="0 0 600 240" preserveAspectRatio="none"><path class="slide-rail-back" d="M50 35C180 35 260 205 550 205"/><path class="slide-rail" d="M50 35C180 35 260 205 550 205"/></svg><div class="range-axis"><span>0</span><span>${ctx.t('Your next possibility')}</span><span>X</span></div><span class="range-note">${ctx.t('A scope illustration, not a price scale.')}</span></div></div>`;
}
export function validCompanion(ctx){
 const t=ctx.t;
 return `<div class="motion-tools wrap" hidden data-motion-tools><span>${t('Meet Valid, your curious companion.')}</span><button type="button" data-motion-toggle aria-pressed="false">${t('Pause motion')}</button><button type="button" data-pet-toggle aria-pressed="true">${t('Hide Valid')}</button><button type="button" data-intro-replay hidden>${t('Replay welcome')}</button></div><div class="valid-actor" hidden data-valid aria-hidden="true"><canvas data-valid-canvas></canvas><span class="valid-bubble"></span><span class="valid-web-thread"></span><div class="valid-binary">0101<br>1010<br>0011</div></div><div class="valid-welcome" hidden data-valid-welcome><div class="valid-welcome-copy"><span class="eyebrow">MOOSETVS</span><h2>${t('A small hello. A world of possibilities.')}</h2><p>${t('I’m Valid. Let’s make something great.')}</p></div><button type="button" data-skip-welcome>${t('Skip animation')}</button></div><noscript><p class="wrap valid-nojs">${t('Valid’s animations are optional. Everything you need is right here.')}</p></noscript>`;
}
