import {button,heading,serviceCards,cta,services,pageHero,icon,email} from './components.mjs';
import {projects,projectCards,industryCards,industries,priceCards,process,faqs} from './content.mjs';
import {leadForm,contactAside} from './forms.mjs';
import {demoPages} from './demos.mjs';
export function extendPages(pages) {
 pages[0].body = pages[0].body.slice(0,-cta().length)+`
 <section class="section tinted"><div class="container">${heading('LESS TALK. MORE SHOW.','See what’s possible.','Explore working concepts. Imagine what they could do for your business.','<a class="text-link" href="/work/">See all demo projects</a>')}${projectCards([projects[0],projects[1],projects[4]])}</div></section>
 <section class="section container problems-section"><div>${heading('SOUND FAMILIAR?','Your time is worth<br>more than busywork.')}<p>Small friction adds up. We build practical ways to remove it.</p></div><div class="problem-list">${[['The same questions, all day.','Give customers a helpful first answer with a support assistant.'],['Leads that slip through the cracks.','Capture enquiries and give every conversation a next step.'],['Tools that don’t talk to each other.','Connect your data, bookings and workflows.'],['A website you’ve outgrown.','Make your online presence as good as the business behind it.']].map(([a,b])=>`<div>${icon('check')}<div><h3>${a}</h3><p>${b}</p></div></div>`).join('')}</div></section>
 <section class="section tinted"><div class="container">${heading('BUILT FOR REAL BUSINESSES','Different industries. Shared challenges.','Better bookings, clearer communication and less manual work.','<a class="text-link" href="/industries/">Explore industries</a>')}${industryCards()}</div></section>
 ${process()}<section class="section tinted"><div class="container">${heading('A CLEAR STARTING POINT','An investment with a plan.','Focused starting packages. A written scope before we build.','<a class="text-link" href="/pricing/">All packages & support</a>')}${priceCards()}</div></section>
 <section class="section container">${heading('FROM PROBLEM TO PROTOTYPE','A closer look at the work.','Concept projects that demonstrate a solution, with fictional sample data.')}${projectCards([projects[2],projects[5]],true)}</section>
 <section class="section why-section"><div class="container">${heading('WHY MOOSETVS','Good technology. A practical partner.')}<div class="grid four">${[['Built around your business','Your process shapes the solution, from the first conversation to the final handover.'],['Automation from the start','We look for repetitive steps a dependable system can take off your plate.'],['Direct communication','Clear requirements, shared progress and an agreed next step.'],['Room to grow','Start with a useful solution and extend it when your business needs more.']].map(([h,p])=>`<div><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></div></section>${faqs()}${cta()}`;
 pages.push({path:'services',title:'Services',description:'Explore MooseTVs AI automation, web development, custom software and digital products.',body:pageHero('WHAT WE DO','The right tools.<br>Working together.','One partner for the website your customers see and the systems that keep your business moving.')+`<section class="section container">${serviceCards()}</section>`+process()+cta()});
 const details = {
 'ai-automation':{title:'Less repetition.<br>More possibility.',intro:'AI and workflow automation for the everyday jobs that slow your team down. Start with one useful process and build from there.',blocks:[['Customer support','Handle common questions and collect context for a helpful human follow-up.'],['Lead qualification','Organise inbound enquiries and route them to the right person.'],['Connected workflows','Connect forms, email, CRM tools and data sources through supported integrations.'],['Document & data tasks','Extract and organise information for review, keeping people involved where judgement matters.']],demos:[0,5],note:'Every automation starts with a defined task. We review data access, accuracy limits, human handoff and any API costs before launch.'},
 'web-development':{title:'A website that works<br>as hard as you do.',intro:'A clear, fast and mobile-friendly home for your business. Give visitors a reason to stay and a simple way to get in touch.',blocks:[['Business websites','Introduce your services, answer the right questions and turn interest into enquiries.'],['Landing pages','Focused pages for campaigns, social posts, outreach and printed QR cards.'],['Booking & commerce','Connect booking flows and storefront experiences with your business tools.'],['Multilingual experiences','Plan content, navigation and right-to-left layouts around the people you serve.']],demos:[2,3],note:'Responsive design, semantic content, accessibility and search-engine metadata are part of the foundation. Content and integrations are scoped together.'},
 'custom-software':{title:'Your business.<br>Your way of working.',intro:'When off-the-shelf tools leave gaps, build a system around the people and processes that make your business work.',blocks:[['Dashboards & reporting','Bring the information your team needs into a focused, usable view.'],['Internal business tools','Replace repetitive spreadsheets with workflows designed for your team.'],['Customer portals','Create a clear place for customers to access agreed information and services.'],['APIs & integrations','Connect existing systems through supported, maintainable interfaces.']],demos:[1,4],note:'Custom software is quoted after discovery. We define data, access needs, integrations and handover before implementation.'}
 };
 for(const s of services.slice(0,3)){const d=details[s.id];pages.push({path:`services/${s.id}`,title:s.name,description:`${s.name} by MooseTVs. ${s.description}`,body:pageHero(s.name.toUpperCase(),d.title,d.intro)+`<section class="section container"><div class="grid two feature-grid">${d.blocks.map(([h,p])=>`<article class="feature-card"><span class="icon-tile">${icon(s.icon)}</span><h2>${h}</h2><p>${p}</p></article>`).join('')}</div><p class="scope-note">${d.note}</p></section><section class="section tinted"><div class="container">${heading('TRY THE IDEA','See the experience in action.','Interactive concepts with clearly labelled sample data.')}${projectCards(d.demos.map(i=>projects[i]))}</div></section>`+cta()});}
 pages.push({path:'digital-products',title:'Digital Products & Free Website Starter',description:'Download a free responsive website starter from MooseTVs. Explore practical templates and reusable tools.',body:pageHero('DIGITAL PRODUCTS','Don’t start from zero.','Practical building blocks for your next project. Our first free website starter is ready to explore and download.')+`<section class="section container">${projectCards([projects[6]])}<div class="scope-note"><h2>More tools, built from real needs.</h2><p>Future templates, automation packs and starter kits will grow from the problems we solve. There are no paid products or subscriptions available here yet.</p></div></section>`+cta()});
 pages.push({path:'work',title:'Demo Projects & Portfolio',description:'Try MooseTVs support, booking, restaurant, business, dashboard, workflow and downloadable template demos.',body:pageHero('THE WORK','Explore it.<br>Don’t just imagine it.','Working demos of websites, software and automations. Every project below is a concept, not a paid client case study.')+`<section class="section container">${projectCards(projects,true)}</section>`+cta()});
 pages.push({path:'industries',title:'Business Industries We Serve',description:'Website and automation ideas for restaurants, gyms, salons, clinics, real estate, automotive, stores and professional services.',body:pageHero('YOUR WORLD, OUR STARTING POINT','Built for the way<br>your business works.','Your customers and processes come first. We shape the technology around them.')+`<section class="section container">${industryCards(true)}</section>`+cta()});
 for(const [id,name,desc,use] of industries) pages.push({path:`industries/${id}`,title:`Websites & Automation for ${name}`,description:`MooseTVs helps ${name.toLowerCase()} with business websites and practical automation.`,body:pageHero(name.toUpperCase(),desc,use)+`<section class="section container"><div class="grid three feature-grid">${[['globe','A clear first impression','A mobile-friendly website that introduces your services and makes the next step easy.'],['flow','Fewer manual steps','Organise incoming requests and connect repetitive parts of your daily process.'],['grid','Information in one place','A business tool shaped around what your team needs to see.']].map(([i,h,p])=>`<article class="feature-card"><span class="icon-tile">${icon(i)}</span><h2>${h}</h2><p>${p}</p></article>`).join('')}</div><p class="scope-note">We begin with your process, available tools and requirements. Sensitive-data handling and industry-specific obligations need to be defined before a solution is built.</p></section><section class="section tinted"><div class="container">${heading('EXPLORE A RELATED CONCEPT','A useful starting point.','Demo content only. Your solution would be scoped to your business.')}${projectCards([id==='restaurants'?projects[2]:projects[1],projects[5]])}</div></section>`+cta()});
 pages.push({path:'pricing',title:'Starting Prices & Support Packages',description:'Websites from $399, AI automation from $499 and optional monthly support. MooseTVs custom software is individually quoted.',body:pageHero('STRAIGHTFORWARD STARTING POINTS','Start with what you need.<br>Build from there.','A clear scope and a written proposal before work begins. Choose a starting point and we’ll shape the details together.')+`<section class="section container">${priceCards(true)}</section>`+faqs()+cta()});
 pages.push({path:'about',title:'About MooseTVs',description:'MooseTVs builds websites, custom software and AI automations around real business problems.',body:pageHero('ABOUT MOOSETVS','Useful technology.<br>Real business purpose.','We build websites, software and AI automations that help businesses save time, serve customers better and grow.')+`<section class="section container about-grid"><div><h2>Build. Automate. Scale.</h2><p>MooseTVs brings web development, custom software and AI automation together under one roof. Your customer-facing website and the systems behind it should work together.</p><p>We start with the problem, agree on a practical scope and build a solution you can use. As your needs grow, that foundation can support more connected tools, reusable products and future subscription software.</p></div><div class="about-panel"><p class="eyebrow">OUR APPROACH</p><h2>Start useful.<br>Keep it clear.<br>Make room to grow.</h2><ul class="check-list"><li>${icon('check')}Business needs before technology choices</li><li>${icon('check')}Clear scope and direct communication</li><li>${icon('check')}Demos you can explore for yourself</li><li>${icon('check')}Practical handover and optional support</li></ul></div></section>`+process()+cta()});
 for(const q of [true,false]) pages.push({path:q?'quote':'contact',title:q?'Get a Quote':'Contact',description:q?'Request a MooseTVs project quote. Share your service needs, budget and timeline for a website, automation or custom software.':`Contact MooseTVs at ${email} to discuss websites, software and AI automation.`,body:pageHero(q?'LET’S BUILD SOMETHING USEFUL':'GET IN TOUCH',q?'What could work better<br>in your business?':'A question. An idea.<br>A good place to start.','Tell us a little about it. We’ll help you find a practical next step.')+`<section class="section container contact-layout">${leadForm(q)}${contactAside()}</section>`});
 pages.push({path:'thank-you',title:'Enquiry Received',description:'Your enquiry has been submitted to MooseTVs.',noindex:true,body:pageHero('THANK YOU','Your next chapter<br>starts here.','If you arrived here after submitting the form, your enquiry has been received. We’ll review the details and follow up using the contact information you provided.')+`<section class="section container"><p>Need to add something? Email <a class="text-link" href="mailto:${email}">${email}</a>.</p><div class="button-row">${button('Explore the demos','/work/')}${button('Back to home','/',true)}</div></section>`});
 pages.push({path:'privacy',title:'Privacy Notice',description:'How MooseTVs handles business enquiries, form data and campaign information.',body:pageHero('PRIVACY','Your enquiry.<br>Handled with care.','The information used by this website and how to contact us about it.')+`<article class="container legal-content"><h2>Information you choose to send</h2><p>Contact and quote forms ask for your name, email, company and message. Quote requests can also include a phone number, service, industry, budget, timeline and preferred contact method. Please avoid sending sensitive information, passwords or payment details.</p><h2>Why we use it</h2><p>We use enquiry information to respond, discuss requirements and prepare proposals. Submitting an enquiry does not sign you up for marketing emails.</p><h2>Form handling and email</h2><p>On the deployed site, Netlify processes submissions. Email conversations use Gmail. These providers may process information outside your country. You can also email ${email} directly.</p><h2>Campaign information and cookies</h2><p>If you visit using a campaign link, the form can include its UTM source, medium, campaign, content and term, along with the landing-page path. These values are kept for the current browser tab’s session and sent with your enquiry. This website does not install advertising cookies or third-party analytics scripts. In-page event hooks do not transmit activity to an analytics service.</p><h2>Interactive demos</h2><p>Demos use fictional data. Information typed into a demo stays in the page’s memory and is cleared when you reload or leave. Demo requests do not contact a real business. Please use fictional details.</p><h2>Retention and requests</h2><p>We aim to keep enquiries only as long as needed for the conversation and any resulting project or applicable record-keeping requirements. To ask about access, correction or deletion, contact <a href="mailto:${email}">${email}</a>.</p><h2>Hosting information</h2><p>The hosting provider may process technical connection information to deliver and protect the site. Provider policies apply to their infrastructure. This notice will be updated if the site’s data practices change.</p></article>`});
 pages.push({path:'terms',title:'Website Terms',description:'MooseTVs demo projects, indicative pricing, free starter licence and project agreements.',body:pageHero('WEBSITE TERMS','A clear starting point.','The website introduces our services. A separate written agreement defines any paid project.')+`<article class="container legal-content"><h2>Services and prices</h2><p>Prices are indicative starting points in USD, not fixed offers. Deliverables, timescales, fees, third-party costs, payment terms, ownership and support are confirmed in a written project agreement.</p><h2>Demos and examples</h2><p>Portfolio demos are concepts with fictional data. They do not represent paid clients, actual reservations, live AI systems or verified performance results. Do not rely on demo output for business decisions.</p><h2>Free starter template</h2><p>The downloadable business-page starter is offered under the MIT licence included on its download page. Review and customise it before using it in a live project.</p><h2>Responsible use</h2><p>Please use this website for legitimate enquiries. Do not submit confidential credentials, payment details, harmful content or information you do not have permission to share.</p><h2>Availability and contact</h2><p>We aim to keep information accurate and useful, but offerings may change. Questions can be sent to <a href="mailto:${email}">${email}</a>.</p></article>`});
 pages.push({path:'404',title:'Page Not Found',description:'This page could not be found. Explore MooseTVs services or get in touch.',noindex:true,body:pageHero('404 · PAGE NOT FOUND','Let’s get you<br>back on track.','That page isn’t here. Return home or explore our services.')+`<section class="section container button-row">${button('Back to home','/')}${button('Explore services','/services/',true)}</section>`});
 pages.push(...demoPages());
}
