export const email = 'moosetvs1@gmail.com';
export const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon = (name, cls = '') => {
  const paths = { code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>', spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>', grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>', box:'<path d="m12 3 9 5v8l-9 5-9-5V8l9-5Zm0 9 9-4M12 12 3 8m9 4v9M7.5 5.5l9 5"/>', check:'<path d="m5 12 4 4L19 6"/>', mail:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 7 9 6 9-6"/>', calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-12 4h1m4 0h1"/>', flow:'<rect x="8" y="2" width="8" height="6" rx="2"/><rect x="2" y="16" width="8" height="6" rx="2"/><rect x="14" y="16" width="8" height="6" rx="2"/><path d="M12 8v4M6 16v-4h12v4"/>', globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>', clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>', chat:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3V11a9 9 0 0 1 18 0Z"/><path d="M7 10h10M7 14h6"/>', shield:'<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/>' };
  return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.code}</svg>`;
};
export const button = (label, href='/quote/', secondary=false) => `<a class="button${secondary?' secondary':''}" href="${href}" data-track="cta_click">${label}</a>`;
export const mark = `<span class="brand-mark" aria-hidden="true">m<span>.</span></span>`;
export const brand = `<a href="/" class="brand" aria-label="MooseTVs home">${mark}<span>MooseTVs<span class="brand-dot">.</span></span></a>`;
export const header = (path) => `<a class="skip" href="#main">Skip to content</a><header class="header"><div class="container nav-wrap">${brand}<button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation">${[['Services','services'],['Work','work'],['Industries','industries'],['Pricing','pricing'],['About','about'],['Contact','contact']].map(([n,p])=>`<a href="/${p}/"${path===p?' aria-current="page"':''}>${n}</a>`).join('')}</nav>${button('Get a Quote')}</div></header>`;
export const footer = () => `<footer class="footer"><div class="container footer-top"><div>${brand}<p>Smarter systems.<br>More room to grow.</p><a class="email" href="mailto:${email}" data-track="contact_click">${email}</a></div><div><h2>Explore</h2><a href="/services/">Services</a><a href="/work/">Our work</a><a href="/industries/">Industries</a><a href="/pricing/">Pricing</a></div><div><h2>What we build</h2><a href="/services/ai-automation/">AI automation</a><a href="/services/web-development/">Websites</a><a href="/services/custom-software/">Custom software</a><a href="/digital-products/">Digital products</a></div><div><h2>Let’s connect</h2><a href="/about/">About MooseTVs</a><a href="/contact/">Contact</a><a href="/quote/">Get a quote</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} MooseTVs. Build. Automate. Scale.</span><div><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></div></div></footer>`;
export const heading = (eyebrow, title, text='', extra='') => `<div class="section-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${text?`<p class="section-description">${text}</p>`:''}</div>${extra}</div>`;
export const pageHero = (eyebrow,title,text) => `<section class="page-hero container"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p></section>`;
export const cta = () => `<section class="container cta-section"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>Less busywork.<br>More business.</h2><p>Tell us what’s slowing you down. Let’s build a better way.</p></div><div>${button('Let’s talk about your project')}<a href="mailto:${email}" data-track="contact_click">${email}</a></div></section>`;
export const services = [
  {id:'ai-automation',name:'AI Automation',icon:'spark',tag:'WORK SMARTER',description:'Give repetitive work to a system that doesn’t need a coffee break.',items:['Customer support assistants','Lead capture & follow-ups','Connected business workflows'],path:'/services/ai-automation/'},
  {id:'web-development',name:'Web Development',icon:'globe',tag:'MAKE YOUR FIRST IMPRESSION COUNT',description:'Turn visitors into conversations with a website built for your business.',items:['Business websites & landing pages','Booking & e-commerce front ends','Mobile-first, multilingual experiences'],path:'/services/web-development/'},
  {id:'custom-software',name:'Custom Software',icon:'code',tag:'BUILT AROUND YOU',description:'Bring your team, tools and information together in one place.',items:['Dashboards & internal tools','Customer portals & web apps','API & business-system integrations'],path:'/services/custom-software/'},
  {id:'digital-products',name:'Digital Products',icon:'box',tag:'START A STEP AHEAD',description:'Practical templates and reusable tools to make your next build easier.',items:['Website & dashboard templates','Automation starters','Reusable software components'],path:'/digital-products/'}
];
export const serviceCards = () => `<div class="grid four service-grid">${services.map((s,i)=>`<article class="service-card"><span class="icon-tile">${icon(s.icon)}</span><span class="card-number">0${i+1}</span><h3><a href="${s.path}">${s.name}</a></h3><p>${s.description}</p><ul>${s.items.map(x=>`<li>${x}</li>`).join('')}</ul><a class="text-link" href="${s.path}">Explore service</a></article>`).join('')}</div>`;
export const workflow = () => `<div class="workflow-window"><div class="window-bar"><div class="window-dots" aria-hidden="true"><i></i><i></i><i></i></div><span>YOUR BUSINESS, CONNECTED</span><span class="demo-label">DEMO</span></div><div class="workflow-body"><div class="workflow-title"><div><span class="small-label">WORKFLOW EXAMPLE</span><h3>From hello to next step.</h3></div><span class="icon-tile">${icon('flow')}</span></div><div class="flow-step"><span class="step-icon">${icon('chat')}</span><div><strong>A new enquiry comes in</strong><span>Website form · Customer message</span></div><span class="step-num">01</span></div><div class="flow-line"></div><div class="flow-step active"><span class="step-icon">${icon('spark')}</span><div><strong>AI sorts the details</strong><span>Understands the request · Qualifies the lead</span></div><span class="step-num">02</span></div><div class="flow-line"></div><div class="flow-split"><div class="flow-step"><span class="step-icon">${icon('grid')}</span><div><strong>CRM updated</strong><span>Everything in one place</span></div></div><div class="flow-step"><span class="step-icon">${icon('mail')}</span><div><strong>Follow-up ready</strong><span>A human stays in control</span></div></div></div><div class="workflow-note">${icon('check')} Less copying. Fewer missed conversations.</div></div><div class="window-footer"><span>Designed around your process</span><a href="/demos/automation/">Explore the workflow</a></div></div>`;
