import {icon, button, heading, esc} from './components.mjs';
export const industries = [
 ['restaurants','Restaurants & cafés','Menus that are easy to browse. Reservations that are easy to manage.','Online menus, reservation requests and customer FAQs.'],
 ['gyms','Gyms & fitness studios','Spend more time coaching and less time coordinating.','Class enquiries, trial-session bookings and member portals.'],
 ['salons','Salons & barbers','Keep your calendar organised and your clients informed.','Service menus, booking flows and appointment reminders.'],
 ['clinics','Clinics & practices','Make the administrative side of care easier to navigate.','Practice information, general enquiries and appointment requests.'],
 ['real-estate','Real estate','Give every property enquiry a clear next step.','Property showcases, lead qualification and viewing requests.'],
 ['automotive','Automotive businesses','Connect vehicle enquiries with the right person.','Vehicle listings, service enquiries and customer follow-ups.'],
 ['local-stores','Local stores','Bring the personality of your shop online.','Product showcases, e-commerce front ends and stock dashboards.'],
 ['professional-services','Professional services','Less routine admin. More time for your clients.','Business websites, enquiry routing and client portals.']
];
export const projects = [
 {id:'support',name:'A helpful first conversation.',category:'AI AUTOMATION',description:'An assistant that answers common questions and prepares a human follow-up.',problem:'Repeated questions take time away from customers who need individual help.',solution:'Scripted FAQ answers, sample lead capture and a clear human handoff.',outcome:'Try an enquiry from first question to handoff. No live AI or messages are sent.',visual:'chat'},
 {id:'booking',name:'Your next booking, simplified.',category:'CUSTOM SOFTWARE',description:'Choose a service, pick a time and see the appointment in an admin view.',problem:'Back-and-forth scheduling makes a simple appointment harder than it needs to be.',solution:'A booking flow that connects service selection with a small admin view.',outcome:'Create and cancel a sample appointment. Demo bookings stay in this tab.',visual:'booking'},
 {id:'restaurant',name:'A seat at the table.',category:'WEB DEVELOPMENT',description:'A restaurant concept with a browsable menu and reservation-request flow.',problem:'Customers need to find the menu and request a table without hunting for details.',solution:'A mobile-friendly restaurant page with menu categories and reservations.',outcome:'Browse sample dishes and prepare a reservation request for a fictional restaurant.',visual:'restaurant'},
 {id:'business',name:'A better first impression.',category:'WEB DEVELOPMENT',description:'A local business concept with a clear service offering and simple enquiry.',problem:'A vague business website leaves visitors unsure what to do next.',solution:'A focused page explains services and offers a short enquiry form.',outcome:'Explore a fictional home-services business and try its sample lead form.',visual:'business'},
 {id:'dashboard',name:'One place. The whole picture.',category:'CUSTOM SOFTWARE',description:'A lead dashboard with sample pipeline data, search and status filters.',problem:'Scattered lead information makes it difficult to know what needs attention.',solution:'One dashboard with an accessible chart and searchable table.',outcome:'Filter a fictional pipeline and see summaries respond to your selection.',visual:'dashboard'},
 {id:'automation',name:'From enquiry to action.',category:'AI AUTOMATION',description:'Follow a lead workflow, from incoming form to organised follow-up.',problem:'Copying enquiry details between tools creates unnecessary manual work.',solution:'A workflow connecting capture, qualification, records and follow-up.',outcome:'Run a simulated workflow. No external systems are connected.',visual:'workflow'},
 {id:'template',name:'A practical head start.',category:'DIGITAL PRODUCTS',description:'Download a responsive, dependency-free business landing-page starter.',problem:'Starting from a blank page adds friction to a small website project.',solution:'A readable HTML starter with accessible sections and responsive styles.',outcome:'Download the actual starter file. Free to adapt for personal or commercial projects.',visual:'template'}
];
export const miniVisual = (type) => {
 if(type==='chat') return `<div class="mini-chat"><div class="mini-chat-head">${icon('spark')} Cedar Studio <span>Demo assistant</span></div><div class="bubble user">Can I book a first visit?</div><div class="bubble">Of course. Is a weekday or weekend better for you?</div><div class="mini-input">Ask a question<span>+</span></div></div>`;
 if(type==='booking') return `<div class="mini-booking"><span class="small-label">CEDAR STUDIO · DEMO</span><h4>Make time for yourself.</h4><div class="week-row">${['MON','TUE','WED','THU','FRI'].map((d,i)=>`<span${i===2?' class="chosen"':''}>${d}<b>${12+i}</b></span>`).join('')}</div><div class="time-row"><span>09:00</span><span class="chosen">10:30</span><span>14:00</span></div></div>`;
 if(type==='dashboard') return `<div class="mini-dashboard"><div class="mini-dash-title">Pipeline overview <span>Sample data</span></div><div class="mini-metrics"><div><small>New leads</small><b>12</b></div><div><small>In progress</small><b>8</b></div><div><small>Won</small><b>5</b></div></div><div class="mini-chart" aria-hidden="true">${[35,58,43,74,56,85,69,94].map(h=>`<i class="bar-${h}"></i>`).join('')}</div></div>`;
 if(type==='workflow') return `<div class="mini-flow">${['New enquiry','Qualify lead','Update CRM','Prepare follow-up'].map((n,i)=>`<div><span>${icon(['mail','spark','grid','check'][i])}</span>${n}<b>0${i+1}</b></div>`).join('')}</div>`;
 if(type==='restaurant') return `<div class="mini-site restaurant-mini"><div>OLIVE & EMBER <span>MENU · VISIT</span></div><h4>A little slower.<br>A little more flavour.</h4><p>Seasonal plates. Good company.</p><span class="mini-pill">Explore the menu</span></div>`;
 if(type==='business') return `<div class="mini-site business-mini"><div>NORTHLINE <span>HOME SERVICES</span></div><h4>A home that<br>works for you.</h4><p>Thoughtful repairs. Clear communication.</p><span class="mini-pill">Start your project</span></div>`;
 return `<div class="mini-code"><div>starter.html <span>FREE TEMPLATE</span></div><pre>&lt;section class="hero"&gt;\n  &lt;h1&gt;Your next big idea.&lt;/h1&gt;\n  &lt;p&gt;Built to get you started.&lt;/p&gt;\n&lt;/section&gt;</pre><p>HTML + CSS · Responsive · No dependencies</p></div>`;
};
export const projectCards = (items=projects, detailed=false) => `<div class="grid ${items.length===2?'two':'three'} project-grid">${items.map(p=>`<article class="project-card"><a href="/demos/${p.id}/" class="project-visual visual-${p.visual}" aria-label="Explore ${esc(p.name)} demo">${miniVisual(p.visual)}</a><div class="project-info"><div class="project-meta"><span>${p.category}</span><span class="demo-label">DEMO PROJECT</span></div><h3><a href="/demos/${p.id}/">${p.name}</a></h3><p>${p.description}</p>${detailed?`<dl class="case-details"><dt>The problem</dt><dd>${p.problem}</dd><dt>The solution</dt><dd>${p.solution}</dd><dt>What you can try</dt><dd>${p.outcome}</dd></dl>`:''}<a class="text-link" href="/demos/${p.id}/">${p.id==='template'?'Explore the starter':'Try the demo'}</a></div></article>`).join('')}</div>`;
export const industryCards = (all=false) => `<div class="grid four industry-grid">${industries.slice(0,all?8:6).map(([id,n,desc])=>`<a class="industry-card" href="/industries/${id}/"><span>${icon(id==='restaurants'?'globe':id==='gyms'?'calendar':id==='clinics'?'shield':id==='real-estate'?'grid':'code')}</span><h3>${n}</h3><p>${desc}</p></a>`).join('')}</div>`;
export const prices = [
 ['Starter Website','399','','A professional presence for a business getting started.',['Responsive marketing website','Essential pages & contact form','Basic search-engine setup'],'Web Development'],
 ['Business Website','799','','A tailored website with room for your business to grow.',['Custom design & page structure','Booking or contact integration','Analytics-ready & SEO foundations'],'Web Development'],
 ['AI Automation','499','','One workflow that takes repetitive tasks off your hands.',['Workflow planning & integration','One assistant or automation','Testing & handover'],'AI Automation'],
 ['Website Maintenance','49','/ month','Practical support to keep your website running smoothly.',['Updates & small fixes','Website monitoring','Basic support'],'Maintenance'],
 ['Managed Automation','149','/ month','Keep automations useful as your business changes.',['Workflow monitoring','Prompt & workflow adjustments','Ongoing support'],'Automation Support'],
 ['Custom Software',null,'','A system designed around your requirements.',['Discovery & technical planning','Web apps, portals & dashboards','APIs & business integrations'],'Custom Software']
];
export const priceCards = (all=false) => `<div class="grid three pricing-grid">${prices.slice(0,all?6:3).map(([name,price,period,desc,items,service],i)=>`<article class="price-card ${i===1?'featured':''}">${i===1?'<span class="price-tag">ROOM TO GROW</span>':''}<h3>${name}</h3><p>${desc}</p><div class="price"><span>${price?'Starting from':'Scoped to your business'}</span><strong>${price?'$'+price:'Let’s talk'}</strong><small>${period||(price?'USD':'Request a quote')}</small></div><ul class="check-list">${items.map(t=>`<li>${icon('check')}${t}</li>`).join('')}</ul>${button('Discuss your project','/quote/?service='+encodeURIComponent(service),i!==1)}</article>`).join('')}</div><p class="pricing-note">Indicative starting prices in USD. Final pricing depends on scope, integrations and ongoing requirements, and is agreed in a written proposal. Any third-party costs are discussed before work starts.</p>`;
export const faqItems = [
 ['How long does a project take?','A focused website and a custom business system have different timelines. After a short discovery conversation, you’ll receive a proposed scope, milestones and delivery schedule.'],
 ['Can you work with the tools I already use?','Yes, where those tools provide suitable integrations or APIs. We review access, limitations and any third-party costs before agreeing the solution.'],
 ['What happens after launch?','We hand over the agreed deliverables and explain how they work. Optional website maintenance starts from $49/month, and managed automation support starts from $149/month.'],
 ['Will I own my website or software?','Ownership, source-code access and third-party licences are set out in your project agreement. We discuss these before work begins.'],
 ['Can you build in more than one language?','Yes. We can plan multilingual content, navigation and right-to-left layouts around your audience. Translation scope is agreed as part of the project.'],
 ['Do I need to know exactly what to build?','No. Tell us what your business does and where work slows down. A free initial consultation helps identify a useful starting point.'],
 ['Are these real client projects?','The launch portfolio consists of labelled demo and concept projects. They show an experience, not client testimonials or verified business results.'],
 ['Is hosting included?','Hosting depends on the project. We can help select an appropriate option, including free tiers where suitable. Any hosting, domain or API charges are explained in the proposal.']
];
export const faqs = () => `<section class="section container faq-section"><div>${heading('GOOD QUESTIONS','A little clarity<br>before we start.')}<p>Something else on your mind?</p><a class="text-link" href="/contact/">Get in touch</a></div><div class="faq-list">${faqItems.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
export const process = () => `<section class="section container">${heading('THE PROCESS','Clear steps. Shared direction.','You know what’s happening, what comes next and what you’re getting.')}<ol class="process-grid">${[['Discover','Understand your business, goals and bottlenecks.'],['Plan','Agree on scope, cost and a delivery plan.'],['Build','Develop your solution and share progress.'],['Test','Check the experience and essential workflows.'],['Launch','Put the solution into use and hand it over.'],['Support','Keep improving with optional ongoing care.']].map(([n,d],i)=>`<li><span>0${i+1}</span><h3>${n}</h3><p>${d}</p></li>`).join('')}</ol></section>`;
